### ISSUE TITLE
Enhancement: Parallelize classical value of nonlocal game

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#12]
The following loop inside of the `nonlocal_game.py` file under the `classical_value` function should be parallelized for large nonlocal games. 

```python
        for i in range(num_alice_outputs ** num_bob_inputs):
           ...
           tgval = np.sum(np.amax(pred_alice, axis=0))
            p_win = max(p_win, tgval)
        return p_win
```

This [parallelization is also performed in QETLAB](https://github.com/nathanieljohnston/QETLAB/blob/691036434e88a0bc26d6253d769d29a455dcb921/NonlocalGameValue.m#L128) where indeed the approach to calculating the classical value of a nonlocal game has been inspired from.

**Comment by Shivansh20128** [comment]
Hi @vprusso , this looks interesting. However, it will require some more work than just following what they have done in QETLAB, as there they have used a `parfor` loop, which is a _parallel_ _for_ loop which we is not available in Python. So we need to look for alternatives, like _joblibs_ or _concurrent.futures_. But we might also need to add some dependencies to this project as _joblib_ needs an installation too. Please let me know how we should approach this, if this enhancement is still needed.
Thank You

**Comment by vprusso** [comment]
Hey @Shivansh20128 , 

True, there are multiple approaches one could take for this issue. As you mentioned `joblib` is one. Another might be to use something like `multiprocessing`: 


```py
import multiprocessing

def my_function(x):
    # Just a dummy function, this would be where we would invoke the NLG function.
    return x * x

if __name__ == "__main__":
    data = [1, 2, 3, 4, 5]
    pool = multiprocessing.Pool()  # Create a pool of processes

    result = pool.map(my_function, data)  # This is similar to MATLAB's parfor

    pool.close()  # Close the pool to new tasks
    pool.join()   # Wait for all worker processes to complete

    print(result)
```

I've had varying experiences with being able to write effective `multiprocessing` code, but it might be one of the possible approaches to try here. Happy to hear if you have any specific ways of handling this that you think might be particularly useful or elegant! Thanks again for your interest and help, @Shivansh20128 !

**Comment by Shivansh20128** [comment]
I have added a PR. Can you also assign this to me?
Thank you

**Comment by vprusso** [comment]
Done! :)
