### ISSUE TITLE
Issue : Haar measure in random_density_matrix

### ISSUE THREAD

**Issue by BCasale** [vprusso/toqito#137]
in random_density_matrix the code

```
    # Haar / Hilbert-Schmidt measure.
    gin = np.random.rand(dim, k_param)

    if not is_real:
        gin = gin + 1j * np.random.rand(dim, k_param)

    rho = gin @ np.array(gin).conj().T

    return np.divide(rho, np.trace(rho))
```
does not produce a Haar measure, as the np.random.rand() function provide a uniform distribution over [0,1).
np.random.rand(dim, k_param) should be remplaced by  np.rand.randn(dim, k_param)

**Comment by vprusso** [comment]
Hello @BCasale . Thank you for your comment and for opening up an issue on `toqito`!

Indeed, this is a nice catch, @BCasale ! I've gone ahead and put in a fix here:
https://github.com/vprusso/toqito/pull/138

On another note, the UnitaryFund will be putting on UnitaryHack in the early spring of this year. If you're not familiar, this is a yearly hackathon that focuses on adding new features and fixing bugs for open-source quantum-themed software projects. For the past two years, the `toqito` project has been a participating project, and I hope to include it this year as well.

As is usual with these types of hackathons, certain projects offer cash bounties for their completion. I've had a great time participating in these events as a maintainer, and I hope you consider participating and contributing to toqito when the hackathon occurs!

For context, I'll put the link to last year's UnitaryHack here:
https://unitaryhack.dev/

In the meantime, happy to chat with you about nonlocal games and interesting problems that might lend themselves nicely to `toqito` :)

Closing the issue. Thank you again for your contribution!
