### ISSUE TITLE
Feature: Fidelity of separability

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#141]
The fidelity of separability (also known as the maximum separable fidelity [1, 2]) is an entanglement measure that can be approximated via semidefinite programs outlined in [3]. Ancillary files provided with [3] ([here](https://arxiv.org/src/2303.07911v1/anc)) implement SDPs that approximate the fidelity of separability.  

This task would entail:

1. Adding and generalizing the channel and density matrix SDPs from here and placing them into `state_metrics/fidelity_of_separability.py`. 
2. Adding corresponding unit tests in `tests/test_state_metrics/test_fidelity_of_separability.py`
3. Updating docs in `docs/states.rst` under "Distance Metrics for Quantum States"

[1] [Two-message quantum interactive proofs and the quantum separability problem](https://arxiv.org/abs/1211.6120)
[2] [Quantum interactive proofs and the complexity of separability testing](https://arxiv.org/abs/1308.5788)
[3] [Quantum Steering Algorithm for Estimating Fidelity of Separability](https://arxiv.org/abs/2303.07911)

**Comment by purva-thakre** [comment]
As mentioned in a previous issue, I would like to work on this for the 2023 Unitary Hackathon.

**Comment by vprusso** [comment]
That's great, @purva-thakre ! I have assigned you the task. Looking forward to seeing what you put together here!

**Comment by purva-thakre** [comment]
@vprusso Are pure states supposed to be the only option for the input state to the SDP functions? Or should I also account for the possibility of mixed states as another option?

**Comment by vprusso** [comment]
Hi @purva-thakre. 

Great question! Yes, the input to the SDP could either be a pure or mixed state. I *think* that should be a relatively straightforward feature to support, but of course, if I have a blindspot on that, do let me know if you see some pitfalls that perhaps I do not! And do not hesitate if any more questions pop up!

**Comment by purva-thakre** [comment]
@vprusso Thanks!

![image](https://github.com/vprusso/toqito/assets/66048318/6e0fdcfb-c447-4620-ab92-d5dec368a82e)


This might be a very minor question but what is the advantage of using `request.getfixturevalue` here instead of say manually defining the product state arrays directly for `mark.parametrize`? Saves the trouble of creating `conftest.py`.

**Comment by vprusso** [comment]
Hi @purva-thakre ,

Good question. I would say that the benefit of using `conftest.py` really comes into play if we had many test files where some subset of those test files required the definition of a product state to test against. Using `conftest.py`, we can consolidate the definition of "product state" to one central location instead of redefining it across all of the different test instances. 

Granted, the location in which you are taking the screenshot is from a smaller set of code associated with a paper, so this benefit is not really present there and defining the product state inline would indeed save you from having to create a `conftest.py`. 

Does that make sense?

**Comment by vprusso** [comment]
Here is the page on the docs pertaining to the various verbosity levels:
https://picos-api.gitlab.io/picos/api/picos.modeling.options.html#option-verbosity

The PICOS docs can be a bit frustrating to parse through. Indeed, I've always had an issue with their integrated search (which seems pretty broken to me). I feel your pain :)

Hopefully, that's useful for you.

**Comment by purva-thakre** [comment]
@vprusso Hopefully, this is the last question for this issue. 

Is there a `template` for sphinx-autodoc or a particular workflow I am supposed to follow to build the documentation locally? I can't find the template in the docs directory but it is referenced [ here](https://github.com/vprusso/toqito/blob/master/docs/conf.py#L49). 

I tried to build the documentation by using `make html` or `make clean html` & the autodocsummary for what I introduced is a lot different compared to the already existing functions. 

what is expected
![image](https://github.com/vprusso/toqito/assets/66048318/42218e39-3d15-4220-956c-01d173582e61)

what I got
![image](https://github.com/vprusso/toqito/assets/66048318/2acf6e42-f4e4-4b96-80c2-611f6528a211)

autodocsummary is also adding some files that I did not change. 

![image](https://github.com/vprusso/toqito/assets/66048318/6fd305da-42d2-4d52-91b5-ccd7a06ef0b5)

**Comment by vprusso** [comment]
Hi @purva-thakre, 

The typical workflow for building the docs of `make clean` -> `make html` in the `docs/` folder should be all you need. The issue you are facing:

```
WARNING: [autosummary] failed to import toqito.state_metrics.fidelity_of_separability.
Possible hints:
* ImportError: 
* ModuleNotFoundError: No module named 'toqito.state_metrics.fidelity_of_separability'
* AttributeError: module 'toqito.state_metrics' has no attribute 'fidelity_of_separability'
```

Arises from the fact that the docs are looking for a function name `fidelity_of_separability`, but the file contains two functions with other names (specifically, `state_ppt_extendible_fidelity` and `channel_ppt_extendible_fidelity`).

My suggestion would be to create two files; one as `state_metrics/fidelity_of_separability.py` and `channel_metrics/fidelity_of_separability.py`. Then, inside these files, make sure that the names of the functions you are referring to have the name `def fidelity_of_separability`. This should solve the doc-building error that you are encountering now. 

Logically, this seems to make sense to me, as these two functions are a bit different; one is concerned with the fidelity of states while the other is concerned with the fidelity of channels. 

Does that make sense? Let me know if perhaps you're seeing something here that I might be missing.
