### ISSUE TITLE
Feature : Fidelity of Separability for mixed states

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#166]
The feature in #141 will be fixed by PR #165.

These functions only accept pure states as input. This issue is to work on allowing mixed states as input states. 

More info about the hierarchy is in [Doherty et.al (2003) - A complete family of separability criteria](https://arxiv.org/abs/quant-ph/0308032)

## Make a plan

1. Some kind of a purification circuit using Qiskit or Cirq ? (Ref 3 in #141 has more details)
2. ...... add more here
3. ....... add more here

**Comment by vprusso** [comment]
Closing from https://github.com/vprusso/toqito/pull/165

**Comment by purva-thakre** [comment]
@vprusso I think this one still needs some work. 

I had been having trouble getting the same results as what was in Ref [3] for mixed states. This is why I thought mixed states might need some additional procedure for purification. I noticed there was a new version uploaded for that paper. Those results are similar to what I got. So, I might need to remove the check for mixed states for the functions added in #165.

**Comment by vprusso** [comment]
Thank you for your due dilligence, @purva-thakre . If you think it makes sense to create an issue for the mixed state case, I'd say go for it! Let me know if I can provide any help on the mixed state stuff, and thank you for taking the time to look into this!
