### ISSUE TITLE
Refactor: Permute systems index offset

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#168]
In much the same spirit as https://github.com/vprusso/toqito/issues/145, it would make sense to have a consistent indexing pattern amongst the functions offered in `toqito`. We should also make this change in the `permute_systems.py` file as well. 

That is, the indexing offset for `permute_systems` starts at `1` but to be consistent with the rest of the functions (and indeed, to be more intuitive from the perspective of a Python programmer) it should assume an index starting at `0`.

**Comment by anushkrishnav** [comment]
Can you give me more info on the above? I would love to take this task

**Comment by vprusso** [comment]
Hi @anushkrishnav ,

Of course, thank you for your interest. 

The general idea here is that some functions in `toqito` start with an index offset starting at `1`. This is confusing and not very Pythonic, as most index offsets are expected to begin at `0`. This is because many of the functions in `toqtio` were converted from MATLAB functions (which has the index starting at `1` instead of `0`).

So, the general idea is for us to convert the `permute_systems` function to behave in a way that uses index `0` instead of `1`. This would also ensure that the change does not break anything that depends on this function. 

Does this make sense? I am happy to provide more information/context if helpful. Also, please let me know if you have additional questions. Happy hacking!

**Comment by anushkrishnav** [comment]
Awesome, I will get started into this, I was checking the codebase and do see what you are talking about, will take on this task 

Thanks for  the comment !

**Comment by vprusso** [comment]
No problem at all. Happy hacking, @anushkrishnav !

**Comment by anushkrishnav** [comment]
Is there a sample test case by anychance ?

**Comment by anushkrishnav** [comment]
kindly assigned the issue to me,, Issued a PR with a potential solution ,  if the solution is alright then will finish up the tests and docs and issue a final commit

**Comment by vprusso** [comment]
Hi @anushkrishnav 

There is an entire test suite that runs both `permute_systems` and functions that depend on `permute_systems`. 

If you check in the `perms/tests/` directory, for instance, you will find the corresponding test cases for `permute_systems.py`

You can run the entire test suite from the root directory of the project by running `pytest .`, or, simply run a specific set of tests using `pytest` as well. If you consult the main README file of toqito, it describes how to run the tests. 

Let me know if that helps!

**Comment by anushkrishnav** [comment]
> Hi @anushkrishnav
> 
> There is an entire test suite that runs both `permute_systems` and functions that depend on `permute_systems`.
> 
> If you check in the `perms/tests/` directory, for instance, you will find the corresponding test cases for `permute_systems.py`
> 
> You can run the entire test suite from the root directory of the project by running `pytest .`, or, simply run a specific set of tests using `pytest` as well. If you consult the main README file of toqito, it describes how to run the tests.
> 
> Let me know if that helps!

I will run the test but since the way indexing changes its expected the input changes too right ? My current solution works for the above case, would love to know your thoughts on the fix

**Comment by vprusso** [comment]
Yes, changing the logic of the indexing will surely break some of the existing tests and thereby require the tests to change to accommodate to adapt to the new indexing-by-zero vs. indexing-by-one scheme. 

The only thing in the input that should be changing is the index (the matrices themselves should be fine). Let me know if that doesn't make sense, and feel free to ask any additional questions.

**Comment by anushkrishnav** [comment]
It makes sense, the index will. change to now start from 0 rather than 1 , I will make the necessary changes on test and update the PR

**Comment by vprusso** [comment]
Yes, and all of the test (for the whole project) should pass based on any changes made. Hope that makes sense, and good luck!

**Comment by anushkrishnav** [comment]
Make sense, right now I am working on the lower and upper bound tasks will work on the tests shortly after , Thank you !

**Comment by vprusso** [comment]
If you run the test suite, it will tell you whether or not they pass, and if they don't, it will show you where/how they differ. 

If you wanted to iterate on a specific example you could also just write a separate python script for testing to run/check a specific instance.

**Comment by anushkrishnav** [comment]
> If you run the test suite, it will tell you whether or not they pass, and if they don't, it will show you where/how they differ.
> 
> If you wanted to iterate on a specific example you could also just write a separate python script for testing to run/check a specific instance.

Got it done, All test cases passed for the new changes do check, had to make a lot of changes in functions that was using permute system , went to each of em and made the updates

**Comment by vprusso** [comment]
Cool, I think this is all good to go then on my end!

Thanks again for your contribution, @anushkrishnav , and feel free to merge when you feel like the code is ready! Thank you again!

**Comment by anushkrishnav** [comment]
> Cool, I think this is all good to go then on my end!
> 
> Thanks again for your contribution, @anushkrishnav , and feel free to merge when you feel like the code is ready! Thank you again!

I will check the docs to  make sure i have not left out any, please assign me the issue , I think its done

**Comment by anushkrishnav** [comment]
It was working on this , thank you !!
