### ISSUE TITLE
Feature: Bures angle

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#171]
Calculate the Bures angle is a measure of distance between two quantum states [[1](https://en.wikipedia.org/wiki/Bures_metric)].

The Bures angle can be computed as follows:

```py
def bures_angle(rho: np.ndarray, sigma: np.ndarray) -> float:
    """Returns the Bures angle between two density operators."""
    return np.real(np.arccos(np.sqrt(fidelity(rho, sigma))))
```

As this is a metric, the location for this should be in `state_metrics/bures_angle.py`. Ensure that proper tests in `tests/test_state_metrics/test_bures_angle.py` and documentation in `docs/state_metrics.rst` are included.  

[1]: [Wikipedia: Bures angle](https://en.wikipedia.org/wiki/Bures_metric)

**Comment by epelaaez** [comment]
Hey! Are you looking for people to work on this?

**Comment by vprusso** [comment]
Hi @epelaaez. Yes, by all means, if you'd like to go ahead and attempt this issue, by all means!

Thank you for your interest in `toqito`, and if you enjoy the project, give it a star and let me know if I can help out with using or contributing! Cheers!
