### ISSUE TITLE
Use one reference file for docstrings

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#191]
As stated in #190, use 1 reference file for all references in the docstrings. 

Helps avoid the additional step of adding references for each function as well as duplicated reference errors. 

https://mystmd.org/guide/citations#including-bibtex

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html

**Comment by purva-thakre** [comment]
Can this be assigned to me?

**Comment by vprusso** [comment]
Yep! Thank you as always for your interest and support! Assigned
