### ISSUE TITLE
Update contibuting guide

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#194]
Currently, the `Contributing` guide in the documentation is split into two pages. The [page on RTD links](https://toqito.readthedocs.io/en/latest/getting_started.html#contributing) to another page in `.github`. 

It might be better to split the page on `.github` into a `Code of Conduct` in the documentation and move the contributing info in `.github` to the section in the documentation. 

## Other Things to Add in Docs

- [ ] How to build Sphinx documentation locally? 
- [ ] As stated in #193, add information about how to locally use isort for ordering the imports. The chosen options for isort are in `isort.cfg`. 
- [ ] Remove info about installing via `setup.py` after making sure an editable installation via `pip` uses a better dependency resolver than what's in setuptools. 
- [ ] How to check for code syntax/style. How to use ~~black~~ ruff to format, to check what changes will be made etc. 
- [ ] How to run tests via pytest. 
- [ ] Add info about pylint, pydocstyle + how to check these locally
- [ ] If new functions are added, how to add a docstring + parameter typing (related to #209)

More info will be added later after a make target is created for this and github actions also checks for code syntax etc.

**Comment by vprusso** [comment]
👍 for this one.

**Comment by purva-thakre** [comment]
Linking a comment in another issue. 

https://github.com/vprusso/toqito/issues/204#issuecomment-1780160205

remove instructions for using pip for an editable installation. poetry is a better dependency resolver.
