### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sebgrijalva** [vprusso/toqito#2]
I've been trying to install toqito but I have trouble with the `cvxpy` package. I get the following error:

`ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly
`

Until last week I had no problem installing and using toqito. After some search I tried different combinations of versions of `pip` and `python` with no success. I even tried to install the package on Repl.it and got the same error message.

Can I get a confirmation that a clean install of toqito is still possible and perhaps some way of using it if it's a problem with my computer? (e.g. on Google Colab , although it has python 3.6.9 )

**Comment by vprusso** [comment]
Hi Seb,

Thanks for the question. 

Part of the automated build process is to do a clean build/install, so I can confirm that this works. I would suggest either running `pip install --upgrade toqito` or `pip uninstall toqito` followed by `pip install toqito`. Hope that helps, and let me know if not.

**Comment by sebgrijalva** [comment]
Thanks @vprusso , I was able to run the setup.py install and now have access to the library (I'm running python 3.8.3, is this an issue? I tried it on a different machine with python 3.7 with no trouble).

`pip install toqito` still gives the error message from my first post. Again, this might just be a problem with my configuration, although if you try to install the package on Repl.it you get the same error.

One extra question: why is the __init__.py file empty now? I find that I have to import the attributes one by one. This is ok in principle but I'm used to getting access right away to some attributes

**Comment by vprusso** [comment]
Hmm, strange. Glad you are able to run via `setup.py`, and thank you for letting me know about the `pip install` woes. 

There will be another update to the PyPi server in the next day or so, and I'm hoping that this will solve the issue. 

Regarding your question on the empty `__init__.py` file, you may have to be more specific as to which one you are referring to. Thanks for the comments and questions!

**Comment by vprusso** [comment]
This thread may be of use in resolving the issue for you locally:
https://github.com/pyca/cryptography/issues/5101

**Comment by sebgrijalva** [comment]
Hello,

>This thread may be of use in resolving the issue for you locally:

Thank you, I see its mostly a local issue with `pip`  and `python` versions. Do you think, however, that `toqito` should be able to be loaded into tools like Repl.it and Colab?

>be more specific as to which one you are referring to.

Yes, I am referring to

toqito/__init__.py

If I understood correctly, here one can add attributes that can be loaded as soon as the library is imported. 

I think I have nothing further to add here, If I find something interesting to comment about installation, I'll open another issue. Thanks again for the help!

**Comment by vprusso** [comment]
Great. I'll close this for now, but please let me know if you encounter any further issues. Thanks again for your help!

**Comment by rurz** [comment]
So sorry for this mess, I erroneously linked this issue (No 2) to my reviews I'm doing on the forked code I have of your repo

**Comment by vprusso** [comment]
No worries at all, @rurz. Please reach out if you have any questions about using `toqito`! Cheers.
