### ISSUE TITLE
Label Workflows Properly

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#201]
## Expected Behavior
All the jobs run by Github Actions are available in `.github/workflows/build-test-actions.yml`. They are labeled according to python versions. 

## Actual Behavior
It might be better to instead label the tests according to what is being tested:

- Run tests specific to Toqito (think of a better name)
- Codestyle: pylint, ~~pydocstyle, black, flake8~~ ruff (make both consistent with each other)
- Examples in docstrings (different issue for this: #289 )
- Build artifacts
- Code coverage
- Build documentation (figure out a workflow): Only need RTD Preview for a PR

The goal of this issue is to change how checks appear in a PR. Instead of what appears below, use labels in the above-itemized list. 
![image](https://github.com/vprusso/toqito/assets/66048318/2f253372-e3fa-4616-833d-2ef1c4736011)

https://pre-commit.com/

Edit:~~ `pydocstyle` does not provide any info about the workflow passing.~~ Decided to remove `pydocstyle`.  
![image](https://github.com/vprusso/toqito/assets/66048318/fb60afbf-8bb9-4c5d-acd8-0914da2deca7)

It might also be better if `pylint` orders all errors/warnings alphabetically.

**Comment by vprusso** [comment]
👍 for this one.

**Comment by purva-thakre** [comment]
Another issue to fix here is build deprecation warnings. 

Got the following in https://github.com/vprusso/toqito/actions/runs/6643533857

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
