### ISSUE TITLE
Installing Toqito

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#207]
Based on the struggle in #204, need to figure out how an editable installation of `toqito` should be packaged. 

Using `pip install -e.` did not install all the required packages. As this is a Python package and pip is popular, it would be good to figure this out especially where is pip getting the info from.

One option would be to use `dev_requirements.txt` created from a working installation via poetry. Then use `pip install dev_reqs`.

Last comment in the above linked issue talks about using `poetry` as a better dependency resolver. But if changes are made to `pyproject.toml` before using `poetry lock (in toqito), poetry install`, the newer version of `pyproject.toml` will not be used. 

https://python-poetry.org/docs/faq/#why-is-the-dependency-resolution-process-slow
https://stackoverflow.com/a/73499097/10241324
https://stackoverflow.com/questions/58961497/how-to-update-poetrys-lock-file-without-upgrading-dependencies
https://stackoverflow.com/questions/58708936/pythonpoetry-installation-is-getting-stuck

```
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

```

**Comment by purva-thakre** [comment]
> Using pip install -e. did not install all the required packages. 

this is probably related to versioning syntax. https://github.com/vprusso/toqito/issues/218#issuecomment-1803850011

**Comment by vprusso** [comment]
Hmm. Wondering if we should just use a straight-up `requirements.txt` file instead of `poetry` as a possible solution. 

I'm still not entirely sure I understand the problem in its entirety (that is, I understand the pain point, but I'm not sure what's causing it). Perhaps this is something we can chat about during our next sync, but if you have any insights, let's keep the conversation going here as this seems like a fairly serious one from a usability perspective.

**Comment by purva-thakre** [comment]
>I understand the pain point, but I'm not sure what's causing it

Yeah, same here. 

I thought pinning the versions in the `toml` file would fix it. It is weird though that only certain modules are inaccessible. `toqito` did install when I installed it via `pip` but trying to import some modules led to `ModuleNotFoundError`.

**Comment by purva-thakre** [comment]
Additional SO links for this: 

https://stackoverflow.com/questions/15368054/import-error-on-installed-package-using-setup-py

https://stackoverflow.com/questions/30474804/setuptools-python-setup-py-install-not-copying-all-child-modules

**Comment by vprusso** [comment]
Hmm, yeah so `python setup.py sdist` definitely seems to not include everything in the zip. Why that is is not quite clear to me, but it's definitely an issue of the `sdist` command not creating the files it should. Still looking into it, but that's likely part of the reason.

**Comment by vprusso** [comment]
So I think I know the problem. In `setup.py` we should include these lines:

```py
    package_dir={"": "toqito"},
    packages=setuptools.find_packages(where="toqito"),
```

Doing so, and running the `python setup.py sdist` command does indeed generate the files in the generated zip that were previously missing. I'll make a PR shortly.
