### ISSUE TITLE
Make parameter typing consistent in doc examples

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#209]
This is not consistent. 

Option 1: `toqito/matrix_props/is_positive_definite.py`
https://github.com/vprusso/toqito/blob/master/toqito/matrix_props/is_positive_definite.py
![image](https://github.com/vprusso/toqito/assets/66048318/0d35e0aa-3659-455f-92f7-72f48fa138bf)

Option 2: `toqito/state_metrics/fidelity_of_separability.py`
https://github.com/vprusso/toqito/blob/master/toqito/state_metrics/fidelity_of_separability.py
![image](https://github.com/vprusso/toqito/assets/66048318/49017378-2d38-4339-a876-501248464b28)

**Comment by purva-thakre** [comment]
@vprusso Which of the two available options should be kept?

**Comment by vprusso** [comment]
True, those are different comment styles. Unless there's a compelling reason to switch, let's aim for the one with the least amount of resistance, that is, the one that would incur the least amount of changes in subsequent files to maintain a consistent docstring style. In this case, that would be "Option 1".

**Comment by purva-thakre** [comment]
fixed in #205
