### ISSUE TITLE
Upgrade to Python 3.12

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#216]
Newest version of Python was released on Oct 2, 23. https://www.python.org/downloads/release/python-3120/

It might be good to make changes in toqito to allow Python 3.12. As tested in #215, we do need to wait for numpy to upgrade to the newer version before we make changes to this repo. 

Currently, a Github workflow's virtual environment is installing [`numpy 1.25.2`](https://github.com/vprusso/toqito/actions/runs/6707219148/job/18225247931#step:4:191) but [`numpy 1.26` ](https://numpy.org/news/) released in Sep 2023 has Python 3.12 support. Maybe poetry is forcing an older version of `numpy` due to other package dependencies. 

https://pypi.org/project/numpy/

Note: an easy way to fix the build error in #215 would be to pin a higher `numpy` version.

**Comment by purva-thakre** [comment]
> Maybe poetry is forcing an older version of numpy due to other package dependencies.

This might be fixed by #218

**Comment by purva-thakre** [comment]
As stated in https://github.com/vprusso/toqito/pull/354#issuecomment-1851200269, we have to wait for `cvxopt` to be compatible with `3.12` then only we can upgrade to a newer version of python.

**Comment by Bchass** [comment]
`3.12` now passes: https://github.com/Bchass/toqito/pull/2

**Comment by purva-thakre** [comment]
@Bchass Feel free to add a PR for this. 

I should have had a test PR up after #409. Looks like we did not need to wait for `cvxopt` or `cvxpy`.

**Comment by purva-thakre** [comment]
Fixed by #413

**Comment by purva-thakre** [comment]
@Bchass When you make a pull request, use one of the keywords allowed by github (link below). This will automatically close the referenced issue after the PR is merged. 

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
