### ISSUE TITLE
cvxpy Deprecation Warnings

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#219]
`pytest` is catching quite a few deprecation warnings related to some of the third party packages in a virtual environment of the workflow run. This issue is to keep track of one of these. 

`cvxpy` warning is currently [an open issue](https://github.com/cvxpy/cvxpy/issues/2270).  

```
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.10/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py:136
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.10/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py:136: DeprecationWarning: invalid escape sequence '\i'
    """

../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.10/lib/python3.10/site-packages/cvxpy/reductions/cone2cone/soc2psd.py:49
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.10/lib/python3.10/site-packages/cvxpy/reductions/cone2cone/soc2psd.py:49: DeprecationWarning: invalid escape sequence '\l'
    """
```

**Comment by vprusso** [comment]
My two-cents here is that since this is a `cvxpy` issue, we let the devs over there take care of the warning and update contingent on their progress. I would be wary of deliberately silencing any warnings that might require our attention.

**Comment by purva-thakre** [comment]
@vprusso What's your opinion on `Qiskit` deprecation warnings? It's tangentially related to this issue.

`Qiskit` has way too many deprecation warnings. For example, see the warnings raised at https://github.com/vprusso/toqito/actions/runs/7459174748/job/20294616315#step:7:1478

Keep or suppress?

**Comment by vprusso** [comment]
Hmm, I don't think we should suppress the warnings necessarily as they might be relevant. Yes, they are a bit annoying, but I think keeping them should be fine. I would just be worried if we did suppress them when they were relevant.

**Comment by purva-thakre** [comment]
Going to go ahead and close this as the linked issue in `cvxpy` is now fixed. 

Also verified in the recently merged PR. The warnings we get are related to #222 

https://github.com/vprusso/toqito/actions/runs/8898862814/job/24436923654#step:7:1527
