### ISSUE TITLE
Remove coveralls

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#220]
`coveralls` is listed as a dependency in the `toml` file. 

But this package is not compatible with `py>3.10`. 
https://github.com/TheKevJames/coveralls-python#coveralls-for-python

![image](https://github.com/vprusso/toqito/assets/66048318/389a2b99-e695-4757-ad57-64d04ab16184)

Probably why a warning is raised by pytest in the `3.11` workflow?

https://github.com/vprusso/toqito/actions/runs/6800993611/job/18490827614?pr=212#step:5:668
```
../../../.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/coverage/pytracer.py:223
  /home/runner/.cache/pypoetry/virtualenvs/toqito-QfgmswsN-py3.11/lib/python3.11/site-packages/coverage/pytracer.py:223: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
    self.thread = self.threading.currentThread()
```

**Comment by purva-thakre** [comment]
probably related to #218.

**Comment by vprusso** [comment]
Hmm, I think we can probably remove the `coveralls` dependencies and usage. It looks like the package isn't well-maintained and hasn't been updated in some time. 

Perhaps we can stick with codecov (similarly to how it was done in mitiq?):
https://github.com/unitaryfund/mitiq/pull/301

Any thoughts, @purva-thakre ?

**Comment by purva-thakre** [comment]
@vprusso I am fine with using codecov. Saves me the work of searching for replacements. thanks!
