### ISSUE TITLE
Add Discord channel information to README

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#225]
It would be nice to include a blurb somewhere on the `README.md` file that has information about the ["toqito" channel](https://discord.com/channels/764231928676089909/1172282184833454090) on the UnitaryFund Discord for users to reach out and ask any questions. Something like this 

"""
Want to know more? Check out our [documentation](https://toqito.readthedocs.io/en/latest/) and chat with us on [Discord](http://discord.unitary.fund/).
"""

**Comment by optrudra** [comment]
hey i am interested in this, can you assign it to me.

**Comment by vprusso** [comment]
Hi @optrudra! Thank you for your interest in `toqito`! You are welcome to create a PR for the issues in question that you are interested in tackling without having them explicitly assigned to you. Looking forward to your PRs, and thank you again!
