### ISSUE TITLE
Build status on documentation page is outdated

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#226]
The build status badge appears to be outdated: 
<img width="722" alt="Screenshot 2023-11-09 at 7 16 31 PM" src="https://github.com/vprusso/toqito/assets/1562214/b0a13114-d974-4875-acfe-ae09728add3f">

**Comment by purva-thakre** [comment]
Docs build is also failing in `readme.md`. 

![image](https://github.com/vprusso/toqito/assets/66048318/82555d03-5c9a-41f3-9f30-00458e082d5d)

**Comment by purva-thakre** [comment]
Closing this as it is a duplicate of #254

**Comment by vprusso** [comment]
Ah, that's my bad for the duplicate. Thank you for closing, @purva-thakre !
