### ISSUE TITLE
Automate copyright year

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#229]
In docs, the year is not updated. 

![image](https://github.com/vprusso/toqito/assets/66048318/26158022-0133-41c2-a6e4-285719d39d0a)

Need to make changes to: `LICENSE` and `docs/conf.py`. 

Updating the year could be automated on a yearly basis: https://github.com/marketplace/actions/update-license-copyright-year-s

Another major problem: `docs` was last updated 3 years ago. https://github.com/vprusso/toqito/deployments

**Comment by vprusso** [comment]
An additional thing here is that I don't think it's fair that my name is put next to the copyright. Since its inception in 2020, the project has grown to include many different contributors. I think my name should also be removed from the updated copyright doc.

**Comment by purva-thakre** [comment]
Use this issue to also automate the docs build:

https://github.com/marketplace/actions/sphinx-docs-build-with-readthedocs-docker
https://coderefinery.github.io/documentation/gh_workflow/

**Comment by purva-thakre** [comment]
After #279, this issue is open to automate an update to the copyright year range `2020 - new date`. 

It does appear RTD build is already automated. So, https://github.com/vprusso/toqito/issues/229#issuecomment-1806072500 can be ignored.
