### ISSUE TITLE
Missing `channel_metrics` module

### ISSUE THREAD

**Issue by sebgrijalva** [vprusso/toqito#23]
After an install in a clean environment (`pip install toqito`), the module `channel_metrics` (which is included in the repo) appears to be missing. I can't even find the associated folder if I run `pip show -f toqito`.

**Comment by vprusso** [comment]
Right, the `channel_metrics` module is actively being added in `0.0.7.` The current `toqito` on the PyPi server is `0.0.6`, so that is expected. When `0.0.7` comes out, I'll update the PyPi server so that way the `channel_metrics` folder gets added.

**Comment by vprusso** [comment]
I think this closes the issue, so I'm going to go ahead and close it, but let me know if something isn't clear.
