### ISSUE TITLE
Missing examples in docstrings

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#266]
Not all functions have examples in their docstrings. This issue is to keep track of all of these (~~more to be added to the list~~). 

Example screenshot of examples in `channel_metrics/channel_fidelity`.

![image](https://github.com/vprusso/toqito/assets/66048318/39b17252-ceba-4b91-8ff2-962188977a83)

Link to the same in the docstring of the above function: https://github.com/vprusso/toqito/blob/948218a7f32df6fc182f7241e61a9341b1271c96/toqito/channel_metrics/channel_fidelity.py#L35-L48

To fix one of the following, hover over the item to create a new issue and then add a PR attempting to fix this new issue with a how-to example in the docstring. 

- [x] #269
- [x] #268
- [x] #267
- [ ] ~~`channel_ops/dual_channel` (duplicate)~~
- [x] `toqito/channel_ops/dual_channel.py`
- [x] `toqito/channel_props/is_quantum_channel.py` (partially complete example)
- [x] `toqito/helper/channel_dim.py` (don't add examples, for now)
- [x] `toqito/helper/cvx_kron.py` (don't add examples, for now)
- [x] `toqito/helper/expr_as_np_array.py` (don't add examples, for now)
- [x] `toqito/helper/np_array_as_expr.py` (don't add examples, for now)
- [x] `toqito/helper/npa_hierarchy.py` (don't add examples, for now)
- [x] `toqito/matrices/standard_basis.py`
- [ ] ~~`toqito/matrix_ops/vectors_from_gram_matrix.py`~~ (mistakenly added to the list?)
- [ ] ~~`toqito/matrix_ops/vectors_to_gram_matrix.py`~~ (mistakenly added to the list?)
- [x] `toqito/matrix_props/is_orthonormal.py`
- [x] `toqito/matrix_props/kp_norm.py`
- [x] `toqito/nonlocal_games/extended_nonlocal_game.py`
- [x] `toqito/nonlocal_games/nonlocal_game.py` : not all defined functions have examples in their docstrings
- [x] `toqito/nonlocal_games/quantum_hedging.py` : not all defined functions have examples in their docstrings
- [x] `toqito/nonlocal_games/xor_game.py`: not all defined functions have examples in their docstrings
- [x] `toqito/state_opt/optimal_clone.py` : not all defined functions have examples in their docstrings
- [x] `toqito/state_opt/ppt_distinguishability.py` : not all defined functions have examples in their docstrings
- [x] `toqito/state_props/is_npt.py`

**Comment by purva-thakre** [comment]
@vprusso The functions in `helper` don't show up in the documentation. Do I need to add examples to their docstrings?

**Comment by vprusso** [comment]
Hmm. I think we can keep the helper methods sparse for now. There are probably some there that frankly should be in other spots, but for now, let's streamline it and ignore the examples for the `helper/` content for now.
