### ISSUE TITLE
Make sure URLs in references are linked properly

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#275]
After changes introduced in #228, make sure all links in `articles.bib` show up correctly as links. Currently, some of the URLs are strings because `pybtex` was unable to parse `"\url{some_link}"` correctly.  

The goal of this issue is to figure out what format works for URLs in `sphinxcontrib-bibtex` and is also compatible with `pybtex`. Then, apply those changes to most of the `@misc` refs in `articles.bib`.

**Comment by vprusso** [comment]
Is this still an issue? If so, are there specific links that are rendering in this way as an example? ( @purva-thakre )

**Comment by purva-thakre** [comment]
@vprusso Yes, this is still relevant. I don't think this is high priority though. 

Some links on the [references page of the docs](https://toqito.readthedocs.io/en/latest/references.html) are not clickable. For example, all the Wikipedia links:

![image](https://github.com/user-attachments/assets/e379a4d3-260f-422a-8fee-e362ba733dfc)

**Comment by vprusso** [comment]
Ah, okay. I think I know why. It looks like the `url` entry in the `refs.bib` file is empty. I'll go ahead and make a fix for this. Thanks for the clarification!

**Comment by vprusso** [comment]
So far so good:
https://github.com/vprusso/toqito/pull/827

I'll keep adding the references and hope that nothing breaks :P
