### ISSUE TITLE
Feature: Matsumoto fidelity

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#28]
The Matusmoto fidelity was introduced in arXiv:1006.0302. In arXiv:2006.06918, it was shown that it is possible to compute this quantity by means of a semidefinite program. Refer to equation 1.11 in the aforementioned preprint. 

The functionality for this feature should be included under `state_metrics/matumoto_fidelity.py`. To solve the semidefinite program, it will most likely make sense to make use of the `cvxpy` module that is used elsewhere in `toqito` to solve similar semidefinite programs. For instance, consult the `state_metrics/fidelity.py` file to see how this function operates, how it invokes the SDP solver, etc. 

Ensure proper testing is in place and 100% test coverage is obtained by creating a unit test file in `tests/test_state_metrics/test_matusmoto_fidelity.py`. Ensure to add `toqito.state_metrics.matusmoto_fidelity` under "Distance Metrics for Quantum States" in `/docs/states.rst`

**Comment by dfacoet** [comment]
I would like to do this. 

It should be pretty similar to `fidelity`, the main differences being that the variable in the SDP is Hermitian, and that the direct calculation can only be used if at least one of the density matrices is non-singular.
Does this sound right?

**Comment by vprusso** [comment]
Hi @dfacoet. That's great to hear, thank you for taking an interest in this feature!

And yes, I believe your initial assessment of this task seems pretty spot on. For what it's worth, it may also be worth comparing with another implementation of this metric as implemented by [QETLAB](http://www.qetlab.com/MatsumotoFidelity). If you have access to MATLAB, you can check your implementation against the QETLAB one, and even if you don't, I think the code itself is well-written and should serve as a guidepost for how to implement it. 

Hope that helps, and please do not hesitate to ping me if you have any questions. Thanks again for your interest, and looking forward to seeing what you come up with!

**Comment by vprusso** [comment]
Closing as this has been implemented. Thank you, @dfacoet!
