### ISSUE TITLE
Automate examples in Docs

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#289]
Right now, all the examples in the documentation are hard-coded such that the output of a function is manually inserted. 

For example, the to-be calculated values of `channel_fidelity` are already in the docstring. 

https://github.com/vprusso/toqito/blob/63ba15d420c3d8f83a87d5de1edf508bb3457d8e/toqito/channel_metrics/channel_fidelity.py#L38-L48

We want to instead move toward calculating these whenever the documentation is built. Might need a new Github Actions workflow. 

https://stackoverflow.com/questions/52965999/best-method-for-limiting-float-precision-comparison-in-python-doctest
https://stackoverflow.com/questions/2428618/how-to-test-floats-results-with-doctest
https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html
https://stackoverflow.com/questions/12391390/does-sphinx-run-my-code-on-executing-make-html
https://stackoverflow.com/questions/58189699/use-sphinx-doctest-with-example
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples

- [ ] Make examples in docs executable: `toqito/channel_metrics`
- [ ] Make examples in docs executable: `toqito/channel_ops`
- [ ] Make examples in docs executable: `toqito/channel_props`
- [ ] Make examples in docs executable: `toqito/channels`
- [ ] Make examples in docs executable: `toqito/helper`
- [ ] Make examples in docs executable: `toqito/matrices`
- [ ] Make examples in docs executable: `toqito/matrix_ops`
- [ ] Make examples in docs executable: `toqito/matrix_props`
- [ ] Make examples in docs executable: `toqito/measurement_ops`
- [ ] Make examples in docs executable: `toqito/measurement_props`
- [ ] Make examples in docs executable: `toqito/nonlocal_games`
- [ ] Make examples in docs executable: `toqito/perms`
- [ ] Make examples in docs executable: `toqito/rand`
- [ ] Make examples in docs executable: `toqito/state_metrics`
- [ ] Make examples in docs executable: `toqito/state_ops`
- [ ] Make examples in docs executable: `toqito/state_opt`
- [ ] Make examples in docs executable: `toqito/state_props`
- [ ] Make examples in docs executable: `toqito/states`

**Comment by vprusso** [comment]
That's a great suggestion. Would be good to make sure that the examples in the docstring *actually work* and stay up-to-date.
