### ISSUE TITLE
Feature: Dual channel

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#29]
Given a map (quantum channel) compute the dual of the map. 

As an example, this functionality is present in the QETLAB package. While the implementation there is in MATLAB, the spirit of the implementation should be quite similar to the implementation for `toqito`:
http://www.qetlab.com/DualMap

Write the functionality for this task in `toqito/channel_ops/dual_channel.py` and ensure proper unit tests for this feature are written in `tests/test_channel_ops/test_dual_channel.py`. Also ensure that the automated docs are updated by placing the line `toqito.channel_ops.dual_channel` in `docs/channels.rst` under `Operations on Quantum Channels`.

**Comment by dfacoet** [comment]
Hi @vprusso, I would like to implement this.
To be clear, "dual" here means the adjoint of the superator, which amounts to

- for Kraus operators, taking the adjoint (conjugate+transpose) of each matrix in the list.
- for a Choi matrix, taking the complex conjugate and `swap`ping input and output (with an optional parameter to specify the dimensions).

Is this correct?

**Comment by vprusso** [comment]
Hi @dfacoet. 

That's great to hear, excited to see what you come up with on this feature. 

And yes, I believe your interpretation of what "dual" means in this context is spot on. Please don't hesitate to ping me if you have further questions, and thanks again as always for your eagle eye catches and contributions!

**Comment by dfacoet** [comment]
I should take into account the discussion in #74 regarding the possible Kraus representations. I think the best thing to do is to accept both "one-list" and "two-lists" representation, and the output should have the same forward.
This is pretty straightforward since in any case it amounts to taking the Hermitian conjugates of all matrices.

**Comment by vprusso** [comment]
Closing. Thanks again to @dfacoet for the wonderful PR!
