### ISSUE TITLE
Update information in `Deployments`

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#291]
The info in this screenshot might make a person think the project's documentation is not updated regularly (made that mistake myself). 

![image](https://github.com/vprusso/toqito/assets/66048318/e456dfe2-18be-4910-a8c0-c6e62e144b98)

Considering RTD builds the documentation when a new change is pushed to `master`, might want to change the `Deployments` info to RTD and not github pages. 

The github pages workflow might be for this page: https://vprusso.github.io/toqito/

**Comment by purva-thakre** [comment]
@vprusso I am unassigning myself because that portion is accessed through `Settings`.

**Comment by vprusso** [comment]
Great. That's been disabled and no longer renders on the main page:
![Screenshot 2023-12-13 at 8 11 15 PM](https://github.com/vprusso/toqito/assets/1562214/f3e2ff12-b486-47a7-8ff1-f9584dacb4c0)

**Comment by vprusso** [comment]
Going to close this out as I think that solves it, but re-open if I missed something.
