### ISSUE TITLE
Finish Introductory Tutorial

### ISSUE THREAD

**Issue by sebgrijalva** [vprusso/toqito#3]
I'd like to be assigned to finish the basic operations tutorials. Basically how to define States, Channels and Measurements with `toqito', as already started in the .rst file

**Comment by vprusso** [comment]
Sounds great, Seb. I will be adding to the "Issues" board with some more clearly defined tasks that might be right up your alley. By all means, you don't have to wait for me to get these out there. I'm excited to see what you come up with. Thanks again for your input and contribution.

**Comment by vprusso** [comment]
Hey @sebgrijalva just wanted to see if you happened to make any progress on this task. I wanted to get this out soon, so if you aren't able to, no worries, just wanted to ensure that I can allocate time to do it on my end if so. Cheers!

**Comment by sebgrijalva** [comment]
Hi @vprusso, I will have it finished by this weekend, for the moment i'll upload what I've done on a branch in my fork :)

**Comment by vprusso** [comment]
That's exciting stuff and really neat to hear. Very much looking forward to what you've been putting together! :)

**Comment by sebgrijalva** [comment]
Ok, I included what I wanted to say in this intro. I'm requesting a pull request so we can discuss how to improve it and merge.

**Comment by vprusso** [comment]
Awesome, thank you for the PR! I'll try and spend some time adding comments soon. Thanks!
