### ISSUE TITLE
Feature: Is quantum channel

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#30]
Write a function to determine if a given superoperator is a quantum channel. A valid quantum channel is a superoperator that is both trace-preserving and completely positive. 

This feature should be placed inside of `toqito/channel_props/is_quantum_channel.py` with unit tests inside of `tests/test_channel_props/test_is_channel.py`. Also, ensure that the docs are updated by updating `docs/channels.rst` and placing `toqito.channel_props.is_quantum_channel` under `Properties of Quantum Channels`.

This feature is contingent on implementing: https://github.com/vprusso/toqito/issues/11, which allows one to determine whether a superoperator is trace-preserving. The other component, determining whether a given superoperator is completely positive is found in [is_completely_positive.py](https://github.com/vprusso/toqito/blob/master/toqito/channel_props/is_completely_positive.py)

**Comment by victor-onofre** [comment]
Hi @vprusso, I have made a pull request for this function. I will wait for your comments.

Thank you!

**Comment by vprusso** [comment]
Looks great, @victor-onofre! Just added a few minor comments.

**Comment by victor-onofre** [comment]
Thank you for reviewing my code @vprusso. I have made the changes to the function.

**Comment by vprusso** [comment]
Awesome looks good! Approved!

**Comment by vprusso** [comment]
Closing as this has been approved and integrated.
