### ISSUE TITLE
Feature: Complementary channel

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#31]
Given a map (quantum channel) compute the complementary map. 

As an example, this functionality is present in the QETLAB package. While the implementation there is in MATLAB, the spirit of the implementation should be quite similar to the implementation for `toqito`:
http://www.qetlab.com/ComplementaryMap

Write the functionality for this task in `toqito/channel_ops/complimentary_channel.py` and ensure proper unit tests for this feature are written in `tests/test_channel_ops/test_complimentary_channel.py`. Also ensure that the automated docs are updated by placing the line `toqito.channel_ops.complimentary_channel` in `docs/channels.rst` under `Operations on Quantum Channels`.

**Comment by Shivansh20128** [comment]
I want to work on this issue. Please assign this to me.
Thank you

**Comment by vprusso** [comment]
Of course! Assigned!
