### ISSUE TITLE
Protect branches for RTD build

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#331]
RTD now lets a user access previous versions of the documentation. 

![image](https://github.com/vprusso/toqito/assets/66048318/c956c1e2-bd29-4e13-93b9-05212cb96f26)

These versions are built by creating branches from the tags of these releases. It would be better to protect these branches from being deleted accidentally. 

![image](https://github.com/vprusso/toqito/assets/66048318/caa9a624-3859-4977-934e-1a789be0795f)

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

https://stackoverflow.com/a/35445203

**Comment by purva-thakre** [comment]
@vprusso I am assigning this to you because I don't have access to the settings for this.

**Comment by purva-thakre** [comment]
I re-labelled the branches. The output might appear a bit different compared to what we discussed previously. RTD automatically adds a prepends a `v` if you click on some older version. So, before the output was appearing as `v: v-1.0.5`. 

Now:

![image](https://github.com/vprusso/toqito/assets/66048318/7d45f307-d9e8-4e44-ad4e-e458fc1acfee)

**Comment by vprusso** [comment]
Think we can close this one out based on our solution yesterday. Thanks again, @purva-thakre !
