### ISSUE TITLE
Quantum Repeaters Technology

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [vprusso/toqito#35]
Hello,

I am working on a paper which states that if the intermediates nodes between initial and final nodes are entangled, then there will be an entanglement created between inital and final nodes.

Do we have this kind of functionality developed in this software? If yes, then is there any tutorial available as to how to create nodes and create entanglement between the nodes.

Thanks,
Ganesh Mylavarapu

**Comment by ganeshmylavarapu-qp** [comment]
For example, if there is an entanglement between Alice and Bob, and entanglement between Bob and Charlie. If the two qubits in Bob are entangled, then there is an entanglement created between Alice and Charlie.

**Comment by vprusso** [comment]
Hi @ganeshmylavarapu-qp. I'm not very knowledgeable about quantum repeaters specifically, but if you're looking for a way to model entanglement between three parties you might get some value looking at the functionality pertaining to extended nonlocal games--these abstractions are similar to two-player nonlocal games but where the referee also acts as a participant (the referee would be Charlie in your case). 

Using these types of abstractions it's possible to make claims about the monogamy-of-entanglement (which seems to be something you're kind of hitting on in your question). 

For reference on extended nonlocal games in toqito, you can check out the documentation [here](https://toqito.readthedocs.io/en/latest/nonlocal_games.html#module-toqito.nonlocal_games.extended_nonlocal_game) along with a tutorial on usage [here](https://toqito.readthedocs.io/en/latest/tutorials.extended_nonlocal_games.html).

If you have any questions, let me know. Cheers!
