### ISSUE TITLE
Feature: Is channel unitary

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#37]
Given a quantum channel, determine if it has the property of being unitary. For more information on the definition of a unitary quantum channel, consult example 2.14 in [this textbook](https://cs.uwaterloo.ca/~watrous/TQI/TQI.pdf).

The gist of how to implement the main idea of the function can be performed by first checking if the input to the function is in the form of a Choi matrix. If so, convert it to its corresponding list of Kraus operators. If the length of this list is equal to one, the channel is unitary.

The functionality for this should be created in `channel_props/is_unitary.py` with corresponding unit tests found in `tests/test_channel_props/test_is_unitary.py`. The docs should also be updated in `/docs/channels.rst` under "Properties of Quantum Channels" with `toqito.channel_props.is_unitary.py`

**Comment by victor-onofre** [comment]
Hi @vprusso, I will try to do this feature this week :)

**Comment by vprusso** [comment]
Hi @victor-onofre. Cool, have at it, and have fun! Looking forward to your contributions.

**Comment by victor-onofre** [comment]
I have made a pull request for this function. I will wait for any comments.

Thank you @vprusso!

**Comment by vprusso** [comment]
Looks great! Just a few small comments posted for you. Thanks again for your contributions, @victor-onofre!

**Comment by victor-onofre** [comment]
Thank you so much for reviewing my code @vprusso. I have made the changes to the function.

**Comment by vprusso** [comment]
Awesome, merged! Thanks again for the contribution! :)

**Comment by vprusso** [comment]
Closing as per https://github.com/vprusso/toqito/pull/72
