### ISSUE TITLE
Generate random circulant Gram matrix of specified dimension.

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#379]
**Task**: Function that allows one to generate a random circulant Gram matrix of a requested dimension.

In `toqito/rand`, adding the following function:

```py
import numpy as np

def random_circulant_gram(dim: int) -> np.ndarray:
    # Step 1: Generate a random diagonal matrix with non-negative entries
    diag_mat = np.diag(np.random.rand(dim))
    
    # Step 2: Construct the normalized DFT matrix
    dft_mat = np.fft.fft(np.eye(dim)) / np.sqrt(dim)
    
    # Step 3: Compute the circulant matrix. Since circ_mat is formed from the DFT of a real 
    # diagonal matrix, it should be real
    return np.real(np.conj(dft_mat.T) @ diag_mat @ dft_mat)
```

Would also need to add appropriate tests in `rand/tests` as well adding a link in the `.rst` docs.

**Comment by ankit-pn** [comment]
I would like to work on this, if no one is working on this then pls it to me!
Thanks

**Comment by vprusso** [comment]
Thanks for the interest, @ankit-pn. Assigned!
