### ISSUE TITLE
Cyclic permutation matrix of dimension "d"

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#381]
The following would allow one to create an n-dimensional cyclic permutation matrix.

Ref: https://en.wikipedia.org/wiki/Cyclic_permutation

```py
def cyclic_permutation_matrix(n: int) -> np.ndarray:
    """Create the cyclic permutation matrix P for a given dimension n."""
    p_mat = np.zeros((n, n), dtype=int)
    np.fill_diagonal(p_mat[1:], 1)
    p_mat[0, -1] = 1
    return p_mat
```

Part of me thinks this should go into `matrices/` instead of `perms/` as I think `perms/` will eventually be refactored to include less "matrix-specific" definitions.

**Comment by Bchass** [comment]
I'll take this one on

**Comment by vprusso** [comment]
Sounds great, @Bchass ! 

Have fun, and let us know if you encounter any friction when implementing this. Thank you for the interest in `toqito`, and excited to see what you are able to put together!
