### ISSUE TITLE
ModuleNotFoundError: No module named 'toqito'

### ISSUE THREAD

**Issue by Bchass** [vprusso/toqito#386]
Installed `toqito` via pip and tried to run pytest in the root dir and in specific folder:

`ImportError while importing test module '/Users/bchass/Documents/Forks/toqito/toqito/rand/tests/test_random_ginibre.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/bchass/.pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../__init__.py:2: in <module>
    from toqito.rand.random_unitary import random_unitary
E   ModuleNotFoundError: No module named 'toqito'`

I've reinstalled the package and tried to install with `setup.py` instead which yields the same results.

Pip list for the virtual env:

<img width="302" alt="Screenshot 2023-12-21 at 7 59 33 AM" src="https://github.com/vprusso/toqito/assets/34097574/a8b186b6-8fb4-41f5-9869-f56afa7c4d8b">

I'm not sure what I'm missing, but all tests throw an error.

**Comment by vprusso** [comment]
The version of `toqito` on the PyPi server is going to be different than the one pulled down via GitHub. Specifically, the `toqito.random` path is now `toqito.rand`

You'll want to install `toqito` within the root of the project as:

```
pip install -e .
```

Then you should be able to:

```
from toqito.rand import random_unitary
```

**Comment by Bchass** [comment]
> The version of `toqito` on the PyPi server is going to be different than the one pulled down via GitHub. Specifically, the `toqito.random` path is now `toqito.rand`
> 
> You'll want to install `toqito` within the root of the project as:
> 
> ```
> pip install -e .
> ```
> 
> Then you should be able to:
> 
> ```
> from toqito.rand import random_unitary
> ```

I see. I did a fresh install with `pip install -e .` and I'm still getting the same results. But if I do `from toqito.rand import random_unitary` in a python shell, it works just fine. This leads me to believe the virtual env is the culprit.

**Comment by Bchass** [comment]
Some interesting discoveries - during the process of `pip install -e .`, `cvx` was never installed. Due to this, it also indicated `pytest`, `pytest-cov`, and `scikit-image` were not installed either automatically. Once I manually installed these packages, I was then able to install `cvx` manually and pytest is now working correctly.

**Comment by purva-thakre** [comment]
>during the process of pip install -e ., cvx was never installed.

@Bchass Yes, we are aware of this. https://github.com/vprusso/toqito/issues/207#issuecomment-1803883232

Using `poetry` for installation `toqito` won't cause problems like this.

**Comment by purva-thakre** [comment]
Closing this as the issue appears to be resolved partially. The unresolved portion has an open issue.
