### ISSUE TITLE
Failure on macOS

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#399]
As noted in #374, `toqito.perms` module might not work as intended on `macOS`.  The following test fails on `macOS` which is why it is skipped in a Github workflow for `macOS`. 

https://github.com/vprusso/toqito/blob/8606650b98608330c8b89414f7fb641992517ee4/toqito/perms/tests/test_antisymmetric_projection.py#L20-L23

To fix this issue: Check functions from `toqito.perms` in a `macOS` virtual machine or an actual `macOS` device.  

This could possibly be an issue in `scipy` and/or `numpy`. If this is the case, recreate the issue with a simple reproducible example without using functions in `toqito`. For more info, see https://github.com/numpy/numpy/issues/25395#issuecomment-1865066958)

## Failure Message
```
FAILED toqito/perms/tests/test_antisymmetric_projection.py::test_antisymmetric_projection[3-3-True-expected_result3] - IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 27
```

**Comment by Bchass** [comment]
If no one has taken interest in this issue and is not part of a  project, I'd like to take this one on.

I use a Mac on a daily basis.

**Comment by vprusso** [comment]
Another pair of eyes would be great if you're willing to spare them on this, @Bchass !

Thank you, as always, for your interest and support!
