### ISSUE TITLE
Add more details to module level docstrings

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#449]
Due to the changes introduced in #448 and #440, the docstrings at the top of a `.py` file will appear in the documentation. Most of these docstrings lack details. 

For example,

![image](https://github.com/vprusso/toqito/assets/66048318/9a42edf3-5d3e-436c-9ecf-4c542d210f86)

https://github.com/vprusso/toqito/blob/48fbde1a462482e5c439c80e9e1234c6aa97c456/toqito/states/werner.py#L1

This also affects the docstring in `init` files. 

![image](https://github.com/vprusso/toqito/assets/66048318/2904c6f2-5a1f-4cc1-8269-357705669bd7)

https://github.com/vprusso/toqito/blob/48fbde1a462482e5c439c80e9e1234c6aa97c456/toqito/states/__init__.py#L1

This issue is to add more details to each of the following modules:

- [ ] Add details to the module level docstrings: `toqito/channel_metrics`
- [ ] Add details to the module level docstrings: `toqito/channel_ops`
- [ ] Add details to the module level docstrings: `toqito/channel_props`
- [ ] Add details to the module level docstrings: `toqito/channels`
- [ ] Add details to the module level docstrings: `toqito/helper`
- [ ] Add details to the module level docstrings: `toqito/matrices`
- [ ] Add details to the module level docstrings: `toqito/matrix_ops`
- [ ] Add details to the module level docstrings: `toqito/matrix_props`
- [ ] Add details to the module level docstrings: `toqito/measurement_ops`
- [ ] Add details to the module level docstrings: `toqito/measurement_props`
- [ ] Add details to the module level docstrings: `toqito/nonlocal_games`
- [ ] Add details to the module level docstrings: `toqito/perms`
- [ ] Add details to the module level docstrings: `toqito/rand`
- [ ] Add details to the module level docstrings: `toqito/state_metrics`
- [ ] Add details to the module level docstrings: `toqito/state_ops`
- [ ] Add details to the module level docstrings: `toqito/state_opt`
- [ ] Add details to the module level docstrings: `toqito/state_props`
- [ ] Add details to the module level docstrings: `toqito/states`

**Comment by Shivansh20128** [comment]
Hi @purva-thakre 
I am new to this project. You can assign this issue to me, this way I will also learn many things about the project by going through the documentation, and you can get some good docstrings. It may take a week or so for me to complete this.
Thank You :)

**Comment by vprusso** [comment]
Hi @Shivansh20128, 

Thank you for your interest in the project! And of course, we would be happy for you to make your contributions to `toqito`! Feel free to take your time on the issue, and don't hesitate to reach out and let us know if we can help out! Thank you again, @Shivansh20128 , and looking forward to seeing what you are able to put together!

**Comment by Shivansh20128** [comment]
Thank you so much! 😊
