### ISSUE TITLE
Pure_to_mixed

### ISSUE THREAD

**Issue by gharib85** [vprusso/toqito#46]
if min(row_dim, col_dim) == 1:
This condition means 
bra or ket 
So it give wrong answer to bra 
___________
If col_dim==1: #ket
return   phi * phi.conj().T
If row_dim==1: #bra
 return   (phi.conj().T)*phi

**Comment by vprusso** [comment]
Hi @georgios-ts. Thanks for your comment!

This is perhaps an artifact of unclear documentation on my part--but the input to the `pure_to_mixed` function should only be valid for state vectors (kets) or density matrices.

Perhaps the most direct fix is to make this assumption more explicit than it already is in the docs. A more elaborate and structural change could be to enforce the function to take something less general than a `numpy` array--and instead, take something that corresponds to a specific class. The latter may be more long-term, although it's a bit of a design decision, as I like reducing the overhead on the user. 

Anyway, got off on a tangent there. Hope that makes sense, and let me know if not! Cheers.
