### ISSUE TITLE
Customize `toqito` logo

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#467]
Related to the changes introduced in #466 and #416. We want to customize the logo for light and dark modes. The dark mode color theme for wagtail is different and inverting the colors of the existing logo does not work that well. 

The logo image could be switched depending on which theme is being used: light/dark

See this discussion: https://www.reddit.com/r/tailwindcss/comments/kd9czo/comment/gfw0zxb/?utm_source=share&utm_medium=web2x&context=3

![image](https://github.com/vprusso/toqito/assets/66048318/4c644165-ec4a-4ca2-b2b1-38f1643d5b17)

**Comment by purva-thakre** [comment]
It does not appear like the changes in #466 worked out after #524 

![image](https://github.com/vprusso/toqito/assets/66048318/0aca8d9b-84ad-4529-bd37-98f2181a090e)

**Comment by vprusso** [comment]
I think we can just invert in the `.tex` file and create a logo_light and logo_dark. Attached the dark logo for contrast. Let me know what you think, @purva-thakre 
[logo.pdf](https://github.com/vprusso/toqito/files/15048964/logo.pdf)
![logo](https://github.com/vprusso/toqito/assets/1562214/c12c8a44-7c49-434f-8f40-4262ca6e649d)

**Comment by purva-thakre** [comment]
@vprusso Yes, I did try inverting the colors in the `svg` file. Unfortunately, the lines were not clean if we increase the size of the image. 

https://github.com/vprusso/toqito/pull/466#issuecomment-1933315515

**Comment by vprusso** [comment]
Hmm, interesting. The images there are generated the same way the light one is (except the inverted color of course). Are the lines not clean on the light one either? I figured since it was an SVG it would be a lossless format that would scale well, but is that not the case here?

**Comment by purva-thakre** [comment]
>  I figured since it was an SVG it would be a lossless format that would scale well, but is that not the case here?

I am not too sure about this. I took the SVG toqito logo and inverted the colors. What I got in Inkscape is a bit different than what you provided in your previous comment.

**Comment by purva-thakre** [comment]
Closing this due to #836
