### ISSUE TITLE
Refactor functions in `toqito` to output `np.array` 

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#468]
As noted in https://github.com/vprusso/toqito/pull/459#discussion_r1484730468, functions that are supposed to provide a matrix as an output are not consistent with the type of output. This issue is to make sure the output of all such functions is an `array`. 

In some cases:

1. the output matrix is provided as a `2D` list.
2. the output matrix is provided of type `matrix`This might be due to how older versions of numpy allowed us the choice of `numpy.matrix` or `numpy.array`. Numpy's documentation also advises [against using `numpy.matrix`](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html). 
3. the output matrix is provided of type `array`.

Another helpful discussion on this on SO: https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u

Hover over one of the items below to create a separate issue for that item & assign it to yourself. 1 PR to fix 1 item. 

- [x] #470
- [x] #471
- [x] #497
- [x] #498
- [x] Output of `toqito/rand/random_circulant_gram.py` is a 2D list
- [x] Output of `toqito/rand/random_density_matrix.py` is a 2D list
- [x] Output of `toqito/rand/random_ginibre.py` is a 2D list
- [x] Output of `toqito/rand/random_povm.py` is a 2D list
- [x] Output of `toqito/rand/random_state_vector.py` is a 2D list
- [x] Output of `toqito/rand/random_states.py` is a 2D list
- [x] Output of `toqito/rand/random_unitary.py` is a 2D list
- [ ] Output of `toqito/states/bb84.py` is a 2D list

**Comment by Bchass** [comment]
I don't think the hover functionality is working correctly with the above list?

**Comment by purva-thakre** [comment]
It is! https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#converting-tasks-into-issues

**Comment by Bchass** [comment]
The mp4 you posted won't load for me :/ but this is what I'm seeing on my end. I don't see the icon next to each item in the list to convert.

https://github.com/vprusso/toqito/assets/34097574/507f809c-c277-4faa-a800-d77e65aba40b

**Comment by Bchass** [comment]
> I just realized maybe the problem you are seeing is due to repo permissions for your github profile. Perhaps, @vprusso has to invite you as a collaborator for you to be able to convert items to issues?

Correct, the icon doesn't show on my end.

**Comment by purva-thakre** [comment]
Ok. My apologies for the confusion!

Do you want me to assign you to the currently open issue?

**Comment by Bchass** [comment]
Could you assign me `toqito/matrices/cyclic_permutation.py`?

**Comment by vprusso** [comment]
Commented in the issue thread, but @Bchass if you comment in that issue specifically, we can assign you. It's an oddity of GitHub that that's the way it's done, but 🤷

**Comment by Bchass** [comment]
Here's my comment

**Comment by purva-thakre** [comment]
@Bchass Comment in the other issue: https://github.com/vprusso/toqito/issues/471

**Comment by Bchass** [comment]
Can you assign me `toqito/matrices/gen_gell_mann.py` and `toqito/perms/antisymmetric_projection.py` please.

**Comment by purva-thakre** [comment]
@Bchass Comment on #497 and #498

**Comment by purva-thakre** [comment]
@Bchass Are you interested in working on the remaining items in this issue? If not, I can go ahead and assign it to myself to create one PR to resolve all of them. 

Just wanted to double-check since you figured out what the bug was https://github.com/vprusso/toqito/pull/486#discussion_r1502717356

**Comment by Bchass** [comment]
You can go ahead and create one PR for yourself to resolve. Considering it took almost a month for the most recent ones for to find time for 😅

**Comment by purva-thakre** [comment]
Don't know why `random_circulant_gram` is in the issue description. The output is of type `array`. 

https://github.com/vprusso/toqito/blob/821602e4406bc1bf42998c38139b00c40211d0fb/toqito/rand/random_circulant_gram.py#L35-L39
