### ISSUE TITLE
Output of `toqito/matrices/cyclic_permutation.py` is a 2D list

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#471]

**Comment by purva-thakre** [comment]
[Bchass](https://github.com/Bchass) I can't assign it to you because you don't show up in the suggestions, for some reason.

![image](https://github.com/vprusso/toqito/assets/66048318/cc2222cb-17ea-4068-9afb-470ac3844add)

Let's assume, this is assigned to you.

**Comment by vprusso** [comment]
@purva-thakre yeah, this is a silly thing that Git does where unless the user has commented in the thread, they won't show up. @Bchass if you comment here, you will then show up, and we can subsequently assign the issue to you.

**Comment by Bchass** [comment]
Oh GitHub

**Comment by vprusso** [comment]
> Oh GitHub

Lol, thank you, @Bchass  :)

**Comment by Bchass** [comment]
Do we just want to change on how to call the function? Or add `return np.array` in the code for readability? 

```
>>> from toqito.matrices import cyclic_permutation_matrix
>>> n = 4
>>> k = 3
>>> cyclic_permutation_matrix(n,k)
array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])


>>> cyclic_permutation_matrix = cyclic_permutation_matrix(n, k)
>>> print(cyclic_permutation_matrix)
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
```

**Comment by purva-thakre** [comment]
I haven't really dug into what the cause of this issue is. There is some inconsistency in the output expected by doctest vs what it got. 

If I were to use something similar to what's shown below for the expected output of `cyclic_permutation_matrix`, `make doctest` runs into a failure because it expects a 2D list not an array. 

https://github.com/vprusso/toqito/blob/4416bce906c307185320cd9fac367c046e28bfb1/toqito/matrices/clock.py#L41-L44

**Comment by Bchass** [comment]
I'll see what else I can come up with

**Comment by Bchass** [comment]
This is definitely not a straight forward one. Even when do I get the output to match what is expected, it still fails. Maybe whitespace? I'm still chugging away on this.

**Comment by purva-thakre** [comment]
>Even when do I get the output to match what is expected, it still fails. Maybe whitespace?

If you create a draft PR, we could talk about this more.

**Comment by vprusso** [comment]
Yes, having a specific PR would be helpful as we'd be able to see where/how the failure is occurring. I recall us both working with this before and the whitespace checks are a bit annoyingly specific, so that may be what is going on here as an initial guess.

**Comment by purva-thakre** [comment]
>I recall us both working with this before and the whitespace checks are a bit annoyingly specific, so that may be what is going on here as an initial guess.

Not really. I locally tested the changes in one of the examples in #486. The branch for this PR is not up to date but either way, simply sandwiching the expected output using `array()` is not going to fix it. 

```
Document: autoapi/matrices/cyclic_permutation/index
---------------------------------------------------
**********************************************************************
File "autoapi/matrices/cyclic_permutation/index.rst", line 46, in default
Failed example:
    print(cyclic_permutation_matrix)
Expected:
    array([[0 0 0 1]
     [1 0 0 0]
     [0 1 0 0]
     [0 0 1 0]])
Got:
    [[0 0 0 1]
     [1 0 0 0]
     [0 1 0 0]
     [0 0 1 0]]
**********************************************************************
1 items had failures:
   1 of   9 in default
9 tests in 1 items.
8 passed and 1 failed.

```

The output of the function is a 2D list whereas we want it to be a `np.ndarray`.
