### ISSUE TITLE
Rename shift and clock matrices to gen_pauli_x and gen_pauli_z

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#478]
The terminology for the "shift" and "clock" matrices is not necessarily well known in the quantum computing community, and in the context of quantum information, these matrices are more often referred to as the "generalized Pauli-X" and "generalized Pauli-Z" matrices. We should rename these.

We can still reference the matrices as is done in the functions, but we will want to explicitly point out that the generalized Pauli-X (shift) operator and generalized Pauli-Z (phase) operators are named as such.

**Comment by MohitKambli** [comment]
Hello @vprusso ,
Hope you're doing well.
I would like to work on this issue.
Just wanted to know one thing.
According to the requirement, we need to change the filenames, method names, method calls and comments (shift to gen_pauli_x and clock to gen_pauli_z).
Is that correct or did I misunderstand anything?
Kindly let me know if there's something else to it.

Thanks and Regards,
Mohit Kambli

**Comment by vprusso** [comment]
Hi @MohitKambli . Thank you for the interest in contributing to `toqito`!

Indeed, you got it quite right--it's simply a matter of altering the names from `shift` to `gen_pauli_x` and `clock` to `gen_pauli_z` in the appropriate locations within the project. Should be a fairly slamdunk PR I think. 

The nice benefit is that doing this will serve as a nice exercise in familiarizing yourself with the project. Would welcome additional contributions, feedback, etc. from you as well! Looking forward to your contribution, and thank you again for your interest!

**Comment by MohitKambli** [comment]
Hello @vprusso,
Thank you for clarifying my concerns.
I have made the potential changes to solve this issue and raised a pull request for the same.
If at all there are any changes/inputs required from my end, then do let me know.
Sincere apologies if I have implemented the code changes incorrectly or incompletely.

Thanks and Regards,
Mohit Kambli

**Comment by MohitKambli** [comment]
Hello @vprusso,
Hope you're doing well.
Yes, I did go through @purva-thakre's comments, made changes and proceeded accordingly.
Sincere apologies for the mistakes coming from my end.
If at all there any more changes required, then do let me know.
Thank you for understanding my part.
Hope this commit meets the requirement.

Thanks and Regards,
Mohit Kambli
