### ISSUE TITLE
Installing as an editable program

### ISSUE THREAD

**Issue by paniash** [vprusso/toqito#52]
Hi! Is there a way to install toqito as an editable program. Something along the lines of 

```py
pip install -e .
```

Thanks in advance!

**Comment by vprusso** [comment]
Hi @paniash, 

Thank you for the question. Truth be told, I've never used the `-e` option when running `pip install`. My initial, and perhaps naive thought process, is that this should be natively accessible for any package on the PyPi server. 

I'm also curious about the use case for installing as an editable program. I think it would be preferable to simply pull down a branch of the project and edit this branch as need be for any local changes you wish to make. I could be oversimplifying things here as well though. Hope that makes some semblance of sense!

**Comment by paniash** [comment]
@vprusso Sorry for the late response. With `pip install -e .`, any local changes I make are instantly reflected when executing code (atleast that's how qiskit contributions work). Perhaps this isn't required in toqito's case. Feel free to correct me, I still pretty new to python's package management (coming from a C background).

**Comment by vprusso** [comment]
@paniash. Gotcha. I wasn't aware of this `pip` flag before, so I did a bit of reading on it after your comment. I wasn't able to stumble on a use case where the alternative of cloning and making changes that way would be any different. Of course, this could just be a blind spot on my part, which is likely. 

The internal of Qiskit perhaps lend themselves better to this option for one reason or another? Again, I'm doing a bit of guessing here. In the meantime though, I may close this issue for now if that's okay with you. Thanks for the added context.
