### ISSUE TITLE
Remove sparse matrix classes

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#528]
We want to remove all [`Sparse matrix classes`](https://docs.scipy.org/doc/scipy/reference/sparse.html#sparse-matrix-classes) from functions in `toqito` and refactor the function to use `np.ndarray` instead. 

Related to https://github.com/vprusso/toqito/pull/521#discussion_r1543072900. This issue lists functions not listed in #468.

Below is an itemized list of the files that require these changes. If you are interested in working on one of these, comment with which item you want to work on. A maintainer will assign that item to you.

- [x] #529
- [x] #530
- [x] #531
- [x] #532
- [x] #533
- [x] #534
- [x] #535
- [x] #536
- [x] #537

**Comment by Bchass** [comment]
Can you assign the first two to me please

**Comment by vprusso** [comment]
@Bchass, I converted these all into issues. GitHub, unfortunately, requires you to comment on the issue itself in the thread in order for me to assign you. Once you do that, I can assign them to you. Thanks again for your interest and help, @Bchass!

**Comment by purva-thakre** [comment]
I think this issue is not as complicated as I initially thought. We could simply replace all uses of `sparse.matrix` with `sparse.array`. 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_array.html#scipy.sparse.csr_array
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dia_array.html#scipy.sparse.dia_array
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.lil_array.html#scipy.sparse.lil_array
