### ISSUE TITLE
Missing contributor's guide link in readthedocs page

### ISSUE THREAD

**Issue by paniash** [vprusso/toqito#53]
In [this](https://toqito.readthedocs.io/en/latest/getting_started.html#contributing) page, the link to the contributing guide leads to a "page not found" error. It directs the link to `CONTRIBUTING` instead of `CONTRIBUTING.md` which is why the error persists.

**Comment by vprusso** [comment]
Hi @paniash,

Thank you kindly for catching that issue. I have since updated and fixed it. Nice catch, and thank you for your input!
