### ISSUE TITLE
Why is `macos-latest` job for Python3.10 leading to an error?

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#576]
Noticed the following when all the jobs passed successfully in a PR. The jobs for `macos` in Python3.10 give an error that we should upgrade to the latest version of `pip`. 

![image](https://github.com/vprusso/toqito/assets/66048318/cd51ba65-229e-4dc9-a1cb-7d2a868311d9)

Can't really figure out why the error specifies `python3.10 -m pip install --upgrade pip` when both jobs use `python -m pip install --upgrade pip`

https://github.com/vprusso/toqito/blob/e0aed37964889f706201d12e5a3f2ca07e69e5b4/.github/workflows/build-test-actions.yml#L39

https://github.com/vprusso/toqito/blob/e0aed37964889f706201d12e5a3f2ca07e69e5b4/.github/workflows/build-test-actions.yml#L73

**Comment by purva-thakre** [comment]
Interestingly, Mitiq also gets similar warnings for `macos`.

![image](https://github.com/vprusso/toqito/assets/66048318/519247d0-0978-403d-a115-c9271d6563f5)
https://github.com/unitaryfund/mitiq/actions/runs/8899188557

**Comment by purva-thakre** [comment]
@vprusso Should we downgrade the `macos-latest` version in the runner? I think the notice is related to https://github.com/actions/runner-images/issues/9770#issue-2271788870

**Comment by purva-thakre** [comment]
Per https://github.com/unitaryfund/mitiq/issues/2339#issuecomment-2088718365, this issue might also need to be closed. Will update later today or tomorrow.

**Comment by purva-thakre** [comment]
Went over this with Vincent. The `Notice` does not make sense. If we click on one of the `Annotations` in [`Mitiq`](https://github.com/unitaryfund/mitiq/actions/runs/8899188557), it provides a more verbose output for how the runner is installing things. 

The runner manages to upgrade `pip` on its own, also states the latest version of `pip` was installed but later follows it up with the notice in the screenshot. 

https://github.com/unitaryfund/mitiq/actions/runs/8899188557/job/24437954297#step:3:28

![image](https://github.com/vprusso/toqito/assets/66048318/d30d5186-654b-489e-9fd5-46e6dca0d0de)
![image](https://github.com/vprusso/toqito/assets/66048318/4e871017-ed92-401d-852f-292bb0a14e30)
![image](https://github.com/vprusso/toqito/assets/66048318/1f0749fd-bc23-46af-a90c-b73f90e6df77)

**Comment by vprusso** [comment]
Are we able to close this one out, @purva-thakre ?

Don’t think this one is still an issue but maybe I’m wrong?
