### ISSUE TITLE
Remove sympy dependency

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#586]
As `sympy` is a required install but only used for one function, it might be ideal to use another non-sympy approach to reduce the need to require `sympy` as a dependency. 
https://github.com/vprusso/toqito/blob/39bad5dd0181758ba8696742bae4c7349eb25861/toqito/states/mutually_unbiased_basis.py#L4

We could then remove the dependency from the `toml` file: 
https://github.com/vprusso/toqito/blob/39bad5dd0181758ba8696742bae4c7349eb25861/pyproject.toml#L48

and from the requirements: 
https://github.com/vprusso/toqito/blob/39bad5dd0181758ba8696742bae4c7349eb25861/docs/requirements.txt#L3

**Comment by purva-thakre** [comment]
Based on what I could find, we can use numpy for `primerange`. But I couldn't find a convenient substitute for `isprime` unless you are thinking of defining our own function for this.

It might be easier to keep `sympy` as a dependency instead.

**Comment by vprusso** [comment]
As you mentioned, @purva-thakre , I think either I would need to handroll the solution or use another third party package. For now, let's keep the dependency as you suggested. Closing for now.
