### ISSUE TITLE
Contribution Guide missing

### ISSUE THREAD

**Issue by anushkrishnav** [vprusso/toqito#601]
## Describe the bug
There is no contribution guide on the repo

**Comment by vprusso** [comment]
Hi @anushkrishnav 

There is a contribution guide (you can find the file for this [here](https://github.com/vprusso/toqito/blob/8e2d225898f55c3ffdb15aacd433d923e76ba2c6/docs/contributing.rst#L7) and the rendered docs page for the guide [here](https://toqito.readthedocs.io/en/latest/getting_started.html#contributing)).

I'm going to close out this issue, but feel free to open it back up if you feel the guide is insufficient, and don't hesitate to propose any additional improvements. I appreciate the spirit of opening issues to improve the project if you find any friction anywhere else!

**Comment by anushkrishnav** [comment]
Hey, Sorry for opening the issue I will send in a pr that adds the [doc](https://github.com/vprusso/toqito/blob/8e2d225898f55c3ffdb15aacd433d923e76ba2c6/docs/contributing.rst#L7) to the readme , I later discovered the rendered docs , which is pretty helpful

**Comment by vprusso** [comment]
But the contributing guide is linked in the README:
<img width="878" alt="Screenshot 2024-05-30 at 7 49 47 AM" src="https://github.com/vprusso/toqito/assets/1562214/f776c77f-926e-4ffa-9336-7c4c21b798a2">

**Comment by vprusso** [comment]
Ah, but it's broken. Well, that's not very helpful! :)

**Comment by anushkrishnav** [comment]
ahh yehh ;)
