### ISSUE TITLE
Search inside documentation is broken

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#649]
If I search for something in the search box of the docs, some suggestions show up. The link to these suggestions is [broken](https://toqito.readthedocs.io/en/latest/autoapi/matrices/gen_pauli_x/undefinedautoapi/matrices/gen_pauli_x/index.html). 

![image](https://github.com/vprusso/toqito/assets/66048318/4fb67d14-2bbf-4fc6-afe9-92e9ee43db23)

https://toqito.readthedocs.io/en/latest/autoapi/matrices/gen_pauli_x/index.html

**Comment by purva-thakre** [comment]
This is because the links in the searchbox have a different URL than the correct links. `undefinedautoapi/matrices/gen_pauli_x/index.html` is appended to the working URL when it shows up in the searchbox.

**Comment by vprusso** [comment]
If you copy the link in the search items that show up in the dropdown of the searchbox though, it looks like it has (what should be?) the correct link: 
https://toqito.readthedocs.io/en/latest/#:~:text=matrices.-,gen_pauli_x,-Code%20reference

It does resolve to undefined, but that's still unclear to me at this time as to why.

**Comment by purva-thakre** [comment]
I think this is due to a bug in the documentation theme. 

https://github.com/wagtail/sphinx-wagtail-theme/issues/274

**Comment by vprusso** [comment]
> I think this is due to a bug in the documentation theme.
> 
> [wagtail/sphinx-wagtail-theme#274](https://github.com/wagtail/sphinx-wagtail-theme/issues/274)

Nice catch on this, @purva-thakre. I've opened up a PR here that switches to RTD and has a working search feature. 
https://github.com/vprusso/toqito/pull/836
