### ISSUE TITLE
Feature: S(k) norm

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#73]
Given either a vector or matrix provided as an `np.ndarray` object as input, compute the S(k) norm of this object. 

For a matrix `X`, the S(k) operator norm is defined as shown in 
https://github.com/vprusso/toqito/issues/45#issuecomment-850760074

Further information about the S(k) norm is provided in [arXiv:1207.1479](https://arxiv.org/abs/1207.1479).

The S(k) norm is used as a subroutine to determine if an operator is block-positive which is useful in determining various separability results as was done so in [arXiv:1408.6981](https://arxiv.org/abs/1408.6981).

An implementation of the S(k) vector norm and S(k) matrix norm can be found in the QETLAB package [here](http://www.qetlab.com/SkVectorNorm) and [here](http://www.qetlab.com/SkOperatorNorm), respectively. 

For `toqito`, the S(k) norm should operate on either input as a matrix or a vector. This feature should be included under `matrix_props/sk_norm.py`.

**Comment by vezwork** [comment]
Continuing my work from #45, here is a "cheat sheet" i've prepared to help with computing the S(k) operator norm (this norm is necessary for computing k-block positivity).

Given the following input (X, k, n, and m):
![image](https://user-images.githubusercontent.com/11082236/121781472-f4e09000-cb72-11eb-9ba6-2603848e1981.png)
The following holds and is computable:
![image](https://user-images.githubusercontent.com/11082236/121781512-1ccff380-cb73-11eb-9f0a-5a7d83ad159b.png)
QETLAB's S(k) operator norm implementation also uses a random iterative method and some other tricks, but they  difficult to implement in themselves, so I've ignored them for now.

A convex optimization method can be used. Consider the following (pseudo) python:
```python
rho = cp.Variable(shape=[m,n],hermitian=true)

if (k == 1)
  constraints = [
	  rho >= 0,
	  trace(rho) <= 1,
    PartialTranspose(rho, 2, dim) >= 0,
  ]
else
  constraints = [
	  rho >= 0,
	  trace(rho) <= 1,
    k*kron(PartialTrace(rho, 2, dim), eye(dim(2))) >= rho
  ]

obj = cp.Maximize(trace(rho*X))

# Form and solve problem.
prob = cp.Problem(obj, constraints)
prob.solve()
```
The output of `prob.solve()` needs to be processed into upper/lower bounds, so some further work needs to be done to figure that out. This is my progress in the past week or so!

**Comment by vprusso** [comment]
Hi @vezwork. 

Wonderful work so far, it really looks like you're making a lot of great progress here. I sincerely appreciate you taking the time to write this up and share it. If I can offer some assistance, do let me know, but it really seems like you're much more of an expert on this particular problem than I am, which is wonderful. 

Great work, and please do continue to keep me posted on your progress. Looking forward to seeing what you come up with!
