### ISSUE TITLE
Replace poetry with rye or hatch

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#753]
As discussed with Vincent, we should work on switching away from poetry. 

https://www.stuartellis.name/articles/python-modern-practices/#use-a-project-tool
https://rye.astral.sh/
https://hatch.pypa.io/latest/

**Comment by vprusso** [comment]
The more I've read on hatch and rye, the more I feel like poetry is a good solution and one that offers a "one-stop-shop" for dependency management etc. I'd opt to close this issue unless we have a clear path to updating to either one of these other offerings.
