### ISSUE TITLE
Increase collaboration: Open more issues, add labels, PRs and add a roadmap

### ISSUE THREAD

**Issue by nathanshammah** [vprusso/toqito#8]
- Opening more issues on a wishlist-based asset will help the features desired by the core developer, @vprusso, be more apparent to the community. 
- Open issues could be also on topics on which the core developers are already working on, and could be already assigned (e.g. to @vprusso). 
- Labels, such as "good first issue" or "help wanted" can help someone wandering on the repository get a sense of priorities. - Working with pull requests can be helpful, especially to track code development. 
- Adding a simple roadmap at https://github.com/vprusso/toqito/wiki, similarly to [this](https://github.com/unitaryfund/mitiq/wiki), can help the community get a sense of how maintenance and work is planned.

**Comment by vprusso** [comment]
These are all fantastic suggestions. Thank you for taking the time to compile these and place them here. I will most certainly take you up on these ideas. Thank you again for your input!
