### ISSUE TITLE
Implementing tensor products of an object with itself using fast exponentiation

### ISSUE THREAD

**Issue by tnemoz** [vprusso/toqito#803]
Currently, [the code for tensoring a matrix](https://github.com/vprusso/toqito/blob/dd08a53e76d600532fb7e8ec0be494ad8a8b05ef/toqito/matrix_ops/tensor.py#L135C1-L146C22) with itself is the following:
```python
    # Tensor product one matrix `n` times with itself.
    if len(args) == 2 and isinstance(args[1], int):
        num_tensor = args[1]
        if num_tensor == 1:
            return args[0]
        if num_tensor == 2:
            return np.kron(args[0], args[0])
        if num_tensor >= 3:
            result = np.kron(args[0], args[0])
            for _ in range(2, num_tensor):
                result = np.kron(result, args[0])
        return result
```
In particular, this is implemented in linear time. 

**Describe the solution you'd like**
Using fast exponentiation would reduce the number of operations performed, especially when using large number of tensors. Something along the lines of:

```python
    # Tensor product one matrix `n` times with itself.
    if len(args) == 2 and isinstance(args[1], int):
        num_tensor = args[1]
        if num_tensor == 1:
            return args[0]
        tensored_twice = np.kron(args[0], args[0])
        def fast_exponentiation(mat, t):
            if t == 1:
                return mat
            if t & 1:
                return np.kron(t, fast_exponentiation(tensored_twice, t >> 1))
            return fast_exponentation(tensored_twice, t >> 1)
        return fast_exponentiation(args[0], num_tensor)
```

Though maybe a bit overkill for the number of tensors we generally use, this can still save a few calls to `np.kron` for reasonable numbers of tensors.

**Comment by vprusso** [comment]
That's great! Honestly, tensoring is used so frequently that optimizations like this are worthwhile! Neat trick, and I'm all for seeing this in the code base. Thanks, @tnemoz !
