### ISSUE TITLE
Remove Qiskit as dependency

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#818]
The only place in which the Qiskit package is used is in:
https://github.com/vprusso/toqito/blob/master/toqito/rand/random_states.py

This seems a bit of an excessive dependency for such a small amount of usage. Indeed, the random generation of the state vector should probably just be imported wholesale within this function as they do in the `random_statevector` function from Qiskit:
https://github.com/Qiskit/qiskit/blob/main/qiskit/quantum_info/states/random.py

Then the Qiskit dependency could be removed.

**Comment by tnemoz** [comment]
I don't mind doing it, it seems like it shouldn't take long. Or is it better to leave the "good first issue" issues alone for now, in case someone else would like to give it a shot?

**Comment by purva-thakre** [comment]
@tnemoz I think this issue and #820 are closely related. If you want to create 1 PR to fix both, feel free!
