### ISSUE TITLE
Use of ">>>" before every code line

### ISSUE THREAD

**Issue by Shivansh20128** [vprusso/toqito#834]
**Is your feature request related to a problem? Please describe.**

Hi! I was reading through the documentation of this project and working out the code examples given by copying them and running them on my system. But whenever I copy, first of all, there is no direct button to copy the code, and I have to select the code and then copy it. Even then, the strings ">>>" too get copied along with the code, which I have to remove after pasting manually.
I think the use of strings ">>>" is not essential anymore as generally, people don't use the Python interactive shell anymore and instead prefer IDEs. 

**Describe the solution you'd like**

I would suggest that the use of ">>>" should be stopped and removed, as it has become outdated now to use the Python shell.

**Describe alternatives you've considered**

**Additional context**

Example for such use of the string ">>>" can be seen [here](https://github.com/vprusso/toqito/blob/b07993c6cbe48984239dafa17fd4a15e6a4b7206/docs/tutorials.nonlocal_games.rst?plain=1#L311).
It is just a suggestion that could make things a little easier.

**Comment by purva-thakre** [comment]
We use `>>>` for examples in docstrings to check our code behaves as expected. Whenever a PR is run, `doctest` will run those code blocks.
