### ISSUE TITLE
Error in reference for states.chessboard

### ISSUE THREAD

**Issue by Shivansh20128** [vprusso/toqito#843]
## Before reporting this bug:
- [x] Verify there is not an existing issue for it already
- [x] You are using the latest version of `toqito` with a python version `>=3.10`

## Describe the bug
*A clear and concise description of what the bug is.*
The references given for the states.chessboard are wrong [here](https://toqito.readthedocs.io/en/latest/autoapi/states/chessboard/index.html#module-states.chessboard). The references given actually are meant for w_states, and are not related to chessboard states.

## To Reproduce
*Describe the steps to reproduce the bug. Use [markdown syntax](https://www.markdownguide.org/basic-syntax/#code) with inline code and/or code blocks to make your code readable.* 
See the docs [here](https://toqito.readthedocs.io/en/latest/autoapi/states/chessboard/index.html#module-states.chessboard).

## Expected behavior
*A clear and concise description of what you expected to happen. Use [markdown syntax](https://www.markdownguide.org/basic-syntax/#code) with inline code and/or code blocks to make your code readable.* 
The reference should be related to how chessboard states are defined.

## Screenshots
*If applicable, add screenshots to help explain your problem.*

**Comment by vprusso** [comment]
Hi @Shivansh20128 ,

Thanks for opening this. If you could describe the error you noticed in question, that would be excellent. Thank you again for your contributions to the `toqito` project!

**Comment by Shivansh20128** [comment]
I have described the error above. If you look at the documentation for states.chessboard [here](https://toqito.readthedocs.io/en/latest/autoapi/states/chessboard/index.html#module-states.chessboard), and go below to the references, you will see that the given reference is "W. Dür, G. Vidal, and J. I. Cirac. Three qubits can be entangled in two inequivalent ways. Physical Review A, Nov 2000. URL: http://dx.doi.org/10.1103/PhysRevA.62.062314, [doi:10.1103/physreva.62.062314](https://doi.org/10.1103/physreva.62.062314).". This reference should not be here as it does not relate to Chessboard states. (The reference is actually for w_states).
The references should be modified for this submodule.
Thank You

**Comment by Shivansh20128** [comment]
Okay, thank you. I will give this paper a read because it seems very different than what I thought the chessboard state was. It does not appear to be related to Quantum Chess😳. I am learning a lot of things from this project.
You can close this issue once the changes are made. 
Thank you

**Comment by Shivansh20128** [comment]
Fixed!
