### ISSUE TITLE
Remove `pure_to_mixed` in favor of `vector_to_density_matrix`

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#847]
In favor of both [`pure_to_mixed`](https://github.com/vprusso/toqito/blob/master/toqito/state_ops/pure_to_mixed.py) and [`vector_to_density_matrix`](https://github.com/vprusso/toqito/blob/master/toqito/matrix_ops/vector_to_density_matrix.py) being functionally equivalent, it may make sense to do the following:

1. Remove the `pure_to_mixed` function (along with the associated tests)
2. Replace any usages of `pure_to_mixed` with `vector_to_density_matrix`.
3. Rename `vector_to_density_matrix` to just `to_density_matrix` as the input does not necessarily need to be a vector (indeed, it can even be a density matrix) so it may be misleading to prefix the name with `vector` (and hence should drop).

**Comment by mhaoda** [comment]
I'm a quite new contributor to opensource. I want to try a simple issue at the beginning, can I work on this?

**Comment by purva-thakre** [comment]
Hi @mhaoda, I think it might be better to pick a different issue. Someone else (@Shivansh20128) is interested in fixing this issue as they pointed out the the stuff in the description in the toqito Discord channel.

Good to know you are a new contributor! @vprusso or I could walk you through the steps to resolve a different issue.

**Comment by mhaoda** [comment]
Thanks so much @purva-thakre, I'm totally willing to look at a different issue, could you please provide more information about it?

**Comment by vprusso** [comment]
Appreciate your enthusiasm, @mhaoda !

Depending on @Shivansh20128 's inclinations, we can see if they are planning on tackling this. Alternatively, any of the other issues on the board that have the "good-first-issue" tag are typically low barrier-to-entry tasks that are good entry points to the project. I intend on continuing to add more issues with this tag as well, so do stay tuned. 

If you like, I can tag you on other issues that I put up that might be good candidates for you if you are interested. Let me know, as I don't want to spam you needlessly! :)

**Comment by Shivansh20128** [comment]
Hi! Yes, I will work on this issue after finishing the previous one. I am very close to completing it.
Thank You
