### ISSUE TITLE
Flaky non-local games doctest

### ISSUE THREAD

**Issue by purva-thakre** [vprusso/toqito#873]
![image](https://github.com/user-attachments/assets/bc8377ff-5a5e-415b-a824-3a415114297c)

https://github.com/vprusso/toqito/actions/runs/11489775181/job/31979199481#step:5:3428

Appears to be similar to  #613

**Comment by Shivansh20128** [comment]
Yes, it looks the same as issue 613. I can fix this using the same fix I used there. It is working fine there for the earlier doc-example.
Thank you

**Comment by Shivansh20128** [comment]
Hi @purva-thakre , do you think we should add this fix [here](https://github.com/vprusso/toqito/blob/06b0922d05851e0664f71d676284ab033e13b6cb/docs/tutorials.nonlocal_games.rst?plain=1#L420) too, to avoid facing this error again in future?
