### ISSUE TITLE
Feature: Bures distance

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#9]
One feature that may be of use is the ["Bures distance"](https://en.wikipedia.org/wiki/Bures_metric) calculation.

 This feature would be placed under the `state_metrics/` directory with the name `bures_distance.py`. The function would take as input two density matrices (quantum states) and perform the following calculation:

```
from toqito.state_metrics import fidelity

np.sqrt(2.0 * (1.0 - fidelity(rho_1, rho_2)))
```

where `rho_1` and `rho_2` are density operators and where the `fidelity` function comes from `toqito.state_metrics.fidelity`.

This task would also require adding test coverage for the function along with ensuring it is included in the docs. Refer to the style guide and code contributing guidelines for more information. 

> Hi @vprusso, thank you for the welcoming message. I was searching for more information about the Bures distance and found in this paper [arxiv.org/abs/1304.3334](https://arxiv.org/abs/1304.3334) (equation 4) this definition:
> 
> `d = sqrt[ 2 * (1 - sqrt(fidelity(rho_1, rho_2)) ] `
> 
> Is this the correct definition?
> 
> Also, for the test cases. I can take the test for the `fidelity` function and modify it for this new feature?
> 
> Thank you!

**Comment by victor-onofre** [comment]
Hello, I will participate in the Unitary Hack. I will try to do this feature to start. This is my first participation in an open-source project, so many things are new to me. Probably I will have a lot of questions. Thank you for your patience in advance.

**Comment by vprusso** [comment]
Hi @victor-onofre. Welcome and thank you for considering the toqito project, I am happy to have you on board :).

I would be happy to answer questions for you or point you to the relevant resources to get you up and running. Feel free to ping me if you have questions, and looking forward to seeing your contribution included in the toqito project!

**Comment by victor-onofre** [comment]
Hi @vprusso, thank you for the welcoming message. I was searching for more information about the Bures distance and found in this paper [arxiv.org/abs/1304.3334](https://arxiv.org/abs/1304.3334) (equation 4) this definition:

`d = sqrt[ 2 * (1 - sqrt(fidelity(rho_1, rho_2)) ] `

Is this the correct definition? 

Also, for the test cases. I can take the test for the `fidelity` function and modify it for this new feature?

Thank you!

**Comment by vprusso** [comment]
Hi @victor-onofre. Thanks for your comment. Indeed, I think I had written the pseudo-code for the Bures distance somewhat oddly. I've updated my initial comment and will reproduce that quantity (correctly) below:

```
from toqito.state_metrics import fidelity

np.sqrt(2.0 * (1.0 - fidelity(rho_1, rho_2)))
```

Indeed, equation (1.3) I believe gives the correct formulation of the Bures distance for density matrices (http://sciencewise.info/media/pdf/0711.4286v1.pdf).

Regarding the test cases, I think the ones found in `test_fidelity.py` will serve as a nice starting point. Let me know if you have other questions, and thanks!

**Comment by victor-onofre** [comment]
Hi @vprusso, I have made the new function `bures_distance` and do some testing. I'm having trouble at the moment using: 

`from toqito.state_metrics import bures_distance`

I need to install the version of toqito with the function `bures_distance` in `state_metrics` in my local folder for the testings. How can I do that? I'm a little lost here. Sorry if this is a very basic question.

**Comment by vprusso** [comment]
Hi @victor-onofre. That's great to hear!

You can correct me if I'm wrong here, but I believe you might need to include the following line:

```python
from toqito.state_metrics.bures_distance import bures_distance
```

inside of `state_metrics/__init__.py`. Otherwise, if this line isn't present there, the line that you are attempting to use within your test won't properly resolve. 

Anyway, I *think* that is probably your issue. Of course, correct me if I am wrong, or follow up if you have any other questions. Cheers!

**Comment by victor-onofre** [comment]
Hi @vprusso, thank you so much for the help. I have done a pull request for this function. My first pull request ever!
I will wait for your comments and again thank you for your help.

**Comment by vprusso** [comment]
Hi @victor-onofre. Thank you for the contribution, and congrats on your first pull request! :)

A few things that should be pointed out:

- It looks like the build from your commit failed. You can take a peek at this build log and see what went wrong:
https://travis-ci.com/github/vprusso/toqito/builds/225996160

The build success is tied to a few things, one of which being tied to code style. You can see that the linter mentions:

```
************* Module toqito.state_metrics.bures_distance
toqito/state_metrics/bures_distance.py:12:0: C0301: Line too long (115/100) (line-too-long)
toqito/state_metrics/bures_distance.py:13:0: C0301: Line too long (168/100) (line-too-long)
toqito/state_metrics/bures_distance.py:1:0: C0114: Missing module docstring (missing-module-docstring)
```

Basically just means that there are some lines that are too long and the function should contain a doc-string. You can look at the other functions in `toqito` to see what the general style guidelines are on that front. 

One other thing is I'd like to push for complete coverage of the `bures_distance` function. Referring again to that build link from above, you can see the test coverage for the `bures_distance` function you added to be:

```
toqito/state_metrics/bures_distance.py                 10      1      4      1    85.71%   67, 66->67
```

This line tells you what percentage of the file is covered by tests, and if it's not 100%, then what lines in the function are being missed by your test cases. 

If you can complete test coverage and fix those linter errors, that should fix all the aforementioned. 

Let me know if that doesn't make sense and if you have any other questions. Cheers, and congrats again on your first PR!

**Comment by victor-onofre** [comment]
Thank you for reviewing my code @vprusso.  I have made the changes to the function, but I keep getting this error: 
```
************* Module toqito.state_metrics.bures_distance
toqito/state_metrics/bures_distance.py:10:77: C0303: Trailing whitespace (trailing-whitespace)
toqito/state_metrics/bures_distance.py:15:70: C0303: Trailing whitespace (trailing-whitespace)
toqito/state_metrics/bures_distance.py:16:70: C0303: Trailing whitespace (trailing-whitespace)
toqito/state_metrics/bures_distance.py:17:64: C0303: Trailing whitespace (trailing-whitespace)
toqito/state_metrics/bures_distance.py:18:63: C0303: Trailing whitespace (trailing-whitespace)
```
I have made the changes for the whitespace but I cannot fix it. I think I'm missing something, can you explain the meaning of `Trailing whitespace `? Thank you for the help again!

Here is the build log: [https://travis-ci.com/github/vprusso/toqito/builds/226012423](https://travis-ci.com/github/vprusso/toqito/builds/226012423)

**Comment by vprusso** [comment]
Hi @victor-onofre. Of course, happy to review the code, thank you for contributing. 

Regarding those errors, I can explain them in a bit more detail. Indeed, some of the linter errors can sometimes be a bit hard to decipher. Basically, the lines in question that are being mentioned have extra white space. So, if you move your cursor to the end of any of those lines, you'll see that there is white space that you should remove. 

Depending on what editor/IDE you use, this can be easier/more difficult to detect. The nice thing is that the fix is easy, but I certainly understand the confusion :).

Let me know if that doesn't make sense, or if I can be of more help in elaborating further. Cheers!

**Comment by victor-onofre** [comment]
I finally fix the `Trailing whitespace` problem, it was quite tricky.  I will wait for further comments on the code. 
Thank you @vprusso!

**Comment by vprusso** [comment]
@victor-onofre cool! Those linter issues can really be quite pesky, but they are useful for ensuring the code quality is maintained (necessary evil :) ). 

Added a few more comments on the road for your first PR :)

**Comment by victor-onofre** [comment]
Hi @vprusso, thanks again for checking my code. I have made the changes and added some comments to your review. 
Thank you for your patience!

**Comment by vprusso** [comment]
@victor-onofre Cool! Definitely getting close. Put in a few more comments, but they are all fairly minor ones. Looking overall pretty good though!

**Comment by victor-onofre** [comment]
I have made the changes to the function. It looks like I have many mistakes in the docstring of the function. How can I check for errors there? Is there a way to see a preview or something like that?

I don't know how I didn't see those errors from the start :( 
Thank you for your time @vprusso

**Comment by vprusso** [comment]
Hi @victor-onofre. Awesome, thanks for making those changes!

Regarding how one can catch issues in the docs, I think a good workflow is one where you build the docs locally and inspect any of the files you changed from there. 

Specifically what you would do would be to navigate into the `docs` directory of the `toqito` project. Running `make clean html` will build the docs based on the files that are present in your directory. Once the build finishes (hopefully with no errors) you can navigate to `docs/_build/html/_autosummary` where all of the HTML files generated from your docs build will be placed. You would then be able to inspect any of the HTML files from there. 

Hope that makes sense, and thanks again for your contribution! I approved your PR, so congratulations!

Now that you have a good idea about how things are structured in this project, feel free to dive into one of the tasks on the issues board or to propose a feature request. Thanks again, and looking forward to seeing more of your work in `toqito`!

**Comment by vprusso** [comment]
Closing the issue now that the pull request has gone through. Great work, @victor-onofre!
