### ISSUE TITLE
Add Bloch sphere representation with quantum states

### ISSUE THREAD

**Issue by Shivansh20128** [vprusso/toqito#907]
We should add a bloch sphere representation of the quantum states in the API reference section to give an idea what the state represents. For example, we can add bloch sphere for bell states [here](https://toqito.readthedocs.io/en/latest/autoapi/states/bell/index.html), and other states wherever we can. It will add a visual feature to the docs, which currently is all text and code.

I was also thinking that we could add a quantum state bloch sphere simulator, that could make a block sphere for any quantum state we provide it. It would be a great feature for toqito, because it is a tool used to study objects in quantum information, namely, states, channels, and measurements from the numerical perspective. If we build this simulator, then we can allow users to plot quantum states on a bloch sphere by themselves instead of adding it ourselves. This will add a learning component to the tool.

I did a little digging and found that such simulators do exist like [this](https://bloch.kherb.io/) one made using JavaScript. 

Let me know if you find this interesting.

**Comment by vprusso** [comment]
Hi @Shivansh20128 

Thank you for the suggestion! Hmm, I would be a bit hesitant to include external libraries for things like Bloch sphere simulators just for the purpose of documentation in the interest of keeping things lean. I also believe that the `qutip` package has the capability that you are referring to and could be used to visualize state vectors on the Bloch sphere. 

Also, I'd say that while the Bloch sphere can be helpful, it's visualization usages are somewhat limited to fairly contrived/simple examples of states. For more complicated (i.e. higher-dimensional states) that representation won't translate and indeed this would (I believe) but the typical use-case for dealing with and manipulating quantum states in `toqito`. 

Let me know if you agree or not. Happy to chat further, and thank you for the suggestion!

**Comment by Shivansh20128** [comment]
> I would be a bit hesitant to include external libraries for things like Bloch sphere simulators just for the purpose of documentation in the interest of keeping things lean. 

I was actually going to implement our own simulator. But you're right about keeping things clean specially if `qutip` is already capable of doing this.

> it's visualization usages are somewhat limited to fairly contrived/simple examples of states. For more complicated (i.e. higher-dimensional states) that representation won't translate and indeed this would (I believe) but the typical use-case for dealing with and manipulating quantum states in `toqito`.

Yes, that is true. Bloch spheres would be complicated beyond comprehension some many of the states, so maybe its not worth putting them there.

**Comment by vprusso** [comment]
Closing as we reached a consensus that this issue is likely out of scope.
